apiVersion: v1
kind: ConfigMap
metadata:
  name: health-institute-configmap
  namespace: arogyalink
data:
  nodeEnv: container
  dbHost: health-institute-postgres-service
  dbPort: "5432"
  dbName: health_institute_db
  port: "8083"
  doctorServiceGrpcUrl: doctor-service:50051
  healthInstituteServiceGrpcUrl: 0.0.0.0:50052
  redisHost: redis-service
  redisPort: "6379"
