apiVersion: v1
kind: Service
metadata:
  name: doctor-postgres-service
  namespace: arogyalink
spec:
  selector:
    app: doctor-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
