apiVersion: v1
kind: Service
metadata:
  name: doctor-postgres-external-service
  namespace: arogyalink
spec:
  type: NodePort
  selector:
    app: doctor-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30433
