syntax = "proto3";

package patient;

service PatientService {
  rpc CreatePatient(PatientProfileReq) returns (PatientProfileRes);

  rpc UpdatePatientProfile(UpdatePatientProfileDetailsReq) returns (UpdatePatientProfileDetailsRes);

  rpc GetPatientDetails(GetPatientDetailsReq) returns (GetPatientDetailsRes);

  rpc CreatePatientMedicalRecord(CreatePatientMedicalRecordReq) returns (CreatePatientMedicalRecordRes);

  rpc GetStates(GetStatesReq) returns (GetStatesRes);

  rpc GetDistricts(GetDistrictsReq) returns (GetDistrictsRes);
}

message PatientProfileReq {
  uint32          patientPrimaryKey = 1;
  string          patientId         = 2;
  string          email             = 3;
  string          mobile            = 4;
  string          firstName         = 5;
  optional string middleName        = 6;
  string          lastName          = 7;
}

message PatientProfileRes {
  string patientId = 1;
}

message UpdatePatientProfileDetailsReq {
  string          patientProfileId = 1;
  string          patientId        = 2;
  optional string firstName        = 3;
  optional string middleName       = 4;
  optional string lastName         = 5;
  optional string dateOfBirth      = 6;
  optional uint32 age              = 7;
  optional uint32 gender           = 8;
  optional string profileImage     = 9;
  optional string address          = 10;
  optional uint32 stateId          = 11;
  optional uint32 districtId       = 12;
  optional int32  pincode          = 13;
}

message UpdatePatientProfileDetailsRes {
  string patientId = 1;
}

message GetPatientDetailsReq {
  uint32 patientPrimaryKey = 1;
  string patientId         = 2;

}

message PatientDetails {
  string          patientProfileId = 1;
  string          firstName        = 2;
  optional string middleName       = 3;
  string          lastName         = 4;
  optional string dateOfBirth      = 5;
  optional uint32 age              = 6;
  optional uint32 gender           = 7;
  optional string profileImage     = 8;
  optional string address          = 9;
  optional uint32 stateId          = 10;
  optional string stateName        = 11;
  optional uint32 districtId       = 12;
  optional string districtName     = 13;
  optional int32  pincode          = 14;
}

message GetPatientDetailsRes {
  uint32         patientPrimaryKey = 1;
  string         patientId         = 2;
  PatientDetails patientProfile    = 3;
}

message PatientMedicalRecord {

  uint32          patientPrimaryKey         = 1;
  string          patientId                 = 2;
  uint32          doctorPrimaryKey          = 3;
  string          doctorId                  = 4;
  uint32          healthInstitutePrimaryKey = 5;
  string          healthInstituteId         = 6;
  string          title                     = 7;
  string          diagnosis                 = 8;
  optional string description               = 9;
  string          startedDate               = 10;
}

message PatientMedicalDocuments {
  uint32          documentType = 1;
  string          title        = 2;
  string          documentUrl  = 3;
  optional string documentDate = 4;
}

message PatientMedication {
  string medicationName = 1;
  string dosage         = 2;
  string startDate      = 3;
}

message CreatePatientMedicalRecordReq {
  PatientMedicalRecord             medicalRecord    = 3;
  repeated PatientMedicalDocuments medicalDocuments = 4;
  repeated PatientMedication       medications      = 5;
}

message CreatePatientMedicalRecordRes {
  string patientId = 1;
}

message MasterDataItem {
  uint32 id   = 1;
  string name = 2;
  string code = 3;
}

message GetStatesReq {}

message GetStatesRes{
  repeated MasterDataItem states = 1;
}

message GetDistrictsReq {
  uint32 stateId = 1;
}

message GetDistrictsRes {
  repeated MasterDataItem districts = 1;
}