services:
  auth_postgres:
    image: postgres:16
    container_name: postgres_auth
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    networks:
      - arogyalink-network

  doctor_postgres:
    image: postgres:16
    container_name: postgres_doctor
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: doctor_db
    ports:
      - "5433:5432"
    volumes:
      - doctor_postgres_data:/var/lib/postgresql/data
    networks:
      - arogyalink-network

networks:
  arogyalink-network:
    driver: bridge

volumes:
  auth_postgres_data:
  doctor_postgres_data: