apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: arogyalink
type: Opaque
data:
  dbUsername: cG9zdGdyZXM=
  dbPassword: cG9zdGdyZXM=
  port: ODA4MQ==
  jwtAccessSecret: ZWM5N2ExOTVlZDFhMjlkZWRlZGQxY2RlYzJhMjBmNzkwNThjNTg0ZjEzNmZiOTE0NTI0YjQxOGUwZDY2ZDczYg==
  jwtAccessExpiresIn: MTgwcw==
  jwtRefreshSecret: MTJiNTgyZTNiMzBhMjc4NmU4MmZjODNlOTFhN2E3ODA1ZjE0MjI1NWYxYmExZDRiZGFlNDNlZmQ1MTM1MDFlYg==
  jwtRefreshExpiresIn: MWQ=
  