apiVersion: v1
kind: Secret
metadata:
  name: patient-secret
  namespace: arogyalink
type: Opaque
data:
  mongoInitDbRootUsername: cm9vdA==
  mongoInitDbRootPassword: cm9vdA==
  apiBaseUrl: aHR0cDovL2xvY2FsaG9zdDo4MDgw
  jwtAccessSecret: ZWM5N2ExOTVlZDFhMjlkZWRlZGQxY2RlYzJhMjBmNzkwNThjNTg0ZjEzNmZiOTE0NTI0YjQxOGUwZDY2ZDczYg==
  jwtAccessExpiresIn: MTgwcw==
  jwtRefreshSecret: MTJiNTgyZTNiMzBhMjc4NmU4MmZjODNlOTFhN2E3ODA1ZjE0MjI1NWYxYmExZDRiZGFlNDNlZmQ1MTM1MDFlYg==
  jwtRefreshExpiresIn: MWQ=
