apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patient-pvc
  namespace: arogyalink
spec:
  volumeName: patient-pv
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
