apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: arogyalink
spec:
  selector:
    app: myapp
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
    - protocol: TCP
      port: 5053
      targetPort: 5053
