apiVersion: v1
kind: Secret
metadata:
  name: patient-secret
  namespace: arogyalink
type: Opaque
data:
  nodeEnv: Y29udGFpbmVy
  mongodbUrl: bW9uZ29kYjovL3Jvb3Q6cm9vdEBwYXRpZW50X21vbmdvOjI3MDE3Lw==
  mongodbDatabase: YXJvZ3lhX2xpbmtfcGF0aWVudA==
  mongoInitDbRootUsername: cm9vdA==
  mongoInitDbRootPassword: cm9vdA==
  port: ODA4NA==
  patientServiceGrpcUrl: WVhKdlozbGhiR2x1YTE5b1pXRnNkR2hmYVc1emRHbDBkWFJsWDNObGNuWnBZMlU2TlRBd05UST0=
  apiBaseUrl: aHR0cDovL2xvY2FsaG9zdDo4MDgw
  jwtAccessSecret: ZWM5N2ExOTVlZDFhMjlkZWRlZGQxY2RlYzJhMjBmNzkwNThjNTg0ZjEzNmZiOTE0NTI0YjQxOGUwZDY2ZDczYg==
  jwtAccessExpiresIn: Tgwcw==
  jwtRefreshSecret: MTJiNTgyZTNiMzBhMjc4NmU4MmZjODNlOTFhN2E3ODA1ZjE0MjI1NWYxYmExZDRiZGFlNDNlZmQ1MTM1MDFlYg==
  jwtRefreshExpiresIn: MWQ=
  jwtAlgorithm: SFMyNTY=
  redisHost: cmVkaXM=
  redisPort: NjM3OQ==
