syntax = "proto3";

package doctor;

service DoctorService {
  rpc CreateDoctorProfile(DoctorProfileReq)
  returns (DoctorProfileRes);

  rpc UpdateDoctorBasicDetails(UpdateDoctorBasicDeatilsReq)
  returns (UpdateDoctorBasicDeatilsRes);

  rpc UpdateDoctorProfessionalDetails(UpdateDoctorProfessionalDetailsReq)
  returns (UpdateDoctorProfessionalDetailsRes);
}

message DoctorProfileReq {
  string doctorId = 1;
  string email    = 2;
  string mobile   = 3;

  string          firstName  = 4;
  optional string middleName = 5;
  string          lastName   = 6;
}

message DoctorProfileRes {
  string doctorId = 1;
}

message UpdateDoctorBasicDeatilsReq {
  string          doctorId     = 1;
  optional string firstName    = 2;
  optional string middleName   = 3;
  optional string lastName     = 4;
  optional int32  gender       = 5;
  optional string profileImage = 6;
}

message UpdateDoctorBasicDeatilsRes {
  string doctorId = 1;
}

message UpdateDoctorProfessionalDetailsReq {
  string doctorId            = 1;
  string medicalRegistration = 2;
  int32  registrationCouncil = 3;
  int32  registrationState   = 4;
  int32  registrationYear    = 5;
  int32  licenseStatus       = 6;
}

message UpdateDoctorProfessionalDetailsRes {
  string doctorId = 1;
}