apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doctor-pvc
  namespace: arogyalink
spec:
  volumeName: doctor-pv
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
