syntax = "proto3";

package health_institute;

service HealthInstituteService {
  rpc GetAssociatedHealthInstitutes(GetAssociatedHealthInstitutesReq) returns (GetAssociatedHealthInstitutesRes);
}

message GetAssociatedHealthInstitutesReq {
  uint32 doctorPrimaryKey = 1;
  string doctorId         = 2;
}

message GetAssociatedHealthInstitutesData {
  uint32 healthInstitutePrimaryKey = 1;
  string healthInstituteId         = 2;
  string healthInstituteName       = 3;
  uint32 departmentId              = 4;
  string departmentName            = 5;
  uint32 designationId             = 6;
  string designationName           = 7;
  string joiningDate               = 8;
  uint32 consultationScopeId       = 9;
  string consultationScopeName     = 10;
}

message GetAssociatedHealthInstitutesRes {
  repeated GetAssociatedHealthInstitutesData healthInstitutes = 1;
}