apiVersion: v1
kind: Secret
metadata:
  name: health-institute-secret
  namespace: arogyalink
type: Opaque
data:
  nodeEnv: Y29udGFpbmVy
  dbHost: aGVhbHRoX2luc3RpdHV0ZV9wb3N0Z3Jlcw==
  dbPort: NTQzMg==
  dbUsername: cG9zdGdyZXM=
  dbPassword: cG9zdGdyZXM=
  dbName: aGVhbHRoX2luc3RpdHV0ZV9kYg==
  port: ODA4Mw==
  doctorServiceGrpcUrl: YXJvZ3lhbGlua19kb2N0b3Jfc2VydmljZTo1MDA1MQ==
  healthInstituteServiceGrpcUrl: YXJvZ3lhbGlua19oZWFsdGhfaW5zdGl0dXRlX3NlcnZpY2U6NTAwNTI=
  jwtAccessSecret: ZWM5N2ExOTVlZDFhMjlkZWRlZGQxY2RlYzJhMjBmNzkwNThjNTg0ZjEzNmZiOTE0NTI0YjQxOGUwZDY2ZDczYg==
  jwtAccessExpiresIn: Tgwcw==
  jwtRefreshSecret: MTJiNTgyZTNiMzBhMjc4NmU4MmZjODNlOTFhN2E3ODA1ZjE0MjI1NWYxYmExZDRiZGFlNDNlZmQ1MTM1MDFlYg==
  jwtRefreshExpiresIn: MWQ=
  redisHost: cmVkaXM=
  redisPort: NjM3OQ==
