syntax = "proto3";

package health_institute;

service HealthInstituteService {
  rpc CreateHealthInstituteProfile(CreateHealthInstituteProfileReq) returns (CreateHealthInstituteProfileRes);
}

message CreateHealthInstituteProfileReq {
  uint32 healthInstitutePrimaryKey = 1;
  string healthInstituteId         = 2;
  string healthInstituteName       = 3;
  uint32 healthInstituteType       = 4;
  string email                     = 5;
}

message CreateHealthInstituteProfileRes {
  string healthInstituteId = 1;
}
