syntax = "proto3";

package patient;

service PatientService {
  rpc CreatePatient(PatientProfileReq) returns (PatientProfileRes);
}

message PatientProfileReq {
  uint32          patientPrimaryKey = 1;
  string          patientId         = 2;
  string          email             = 3;
  string          mobile            = 4;
  string          firstName         = 5;
  optional string middleName        = 6;
  string          lastName          = 7;
}

message PatientProfileRes {
  string patientId = 1;
}