apiVersion: apps/v1
kind: Deployment
metadata:
  name: arogyalink-auth-deployment
  namespace: arogyalink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth

  template:
    metadata:
      name: auth-pod
      namespace: arogyalink
      labels:
        app: auth

    spec:
      containers:
        - name: arogyalink-auth
          image: subhamsahadev/arogyalink-auth-service:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1Gi
          ports:
          - containerPort: 8081

          # Environment variables
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: nodeEnv

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: dbHost

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: dbPort

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: dbUsername

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: dbPassword

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: dbName

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: port

            - name: DOCTOR_SERVICE_GRPC_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: doctorServiceGrpcUrl

            - name: HEALTH_INSTITUTE_SERVICE_GRPC_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: healthInstituteServiceGrpcUrl

            - name: PATIENT_SERVICE_GRPC_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: patientServiceGrpcUrl

            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: jwtAccessSecret

            - name: JWT_ACCESS_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: jwtAccessExpiresIn

            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: jwtRefreshSecret

            - name: JWT_REFRESH_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: auth-secret
                  key: jwtRefreshExpiresIn

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: redisHost

            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: auth-configmap
                  key: redisPort
                  
          volumeMounts:
            - name: auth-storage
              mountPath: /usr/src/app/uploads

      volumes:
        - name: auth-storage
          persistentVolumeClaim:
            claimName: auth-pvc