apiVersion: apps/v1
kind: Deployment
metadata:
  name: arogyalink-doctor-deployment
  namespace: arogyalink
spec:
  selector:
    matchLabels:
      app: doctor
  template:
    metadata:
      labels:
        app: doctor
    spec:
      containers:
        - name: arogyalink-doctor
          image: subhamsahadev/arogyalink-doctor-service:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: 8082
            - containerPort: 5051

          # Environment variables
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: doctor-configmap
                  key: nodeEnv

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: doctor-configmap
                  key: dbHost

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: doctor-configmap
                  key: dbPort

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: doctor-secret
                  key: dbUsername

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: doctor-secret
                  key: dbPassword

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: doctor-configmap
                  key: dbName

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: doctor-configmap
                  key: port

            - name: DOCTOR_SERVICE_GRPC_URL
              valueFrom:
                configMapKeyRef:
                  name: doctor-configmap
                  key: doctorServiceGrpcUrl

            - name: HEALTH_INSTITUTE_SERVICE_GRPC_URL
              valueFrom:
                configMapKeyRef:
                  name: doctor-configmap
                  key: healthInstituteServiceGrpcUrl

            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: doctor-configmap
                  key: apiBaseUrl

            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: doctor-secret
                  key: jwtAccessSecret

            - name: JWT_ACCESS_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: doctor-secret
                  key: jwtAccessExpiresIn

            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: doctor-secret
                  key: jwtRefreshSecret

            - name: JWT_REFRESH_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: doctor-secret
                  key: jwtRefreshExpiresIn

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: doctor-configmap
                  key: redisHost

            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: doctor-configmap
                  key: redisPort

          # Volume mount config
          volumeMounts:
            - name: doctor-storage
              mountPath: /usr/src/app/uploads

          # Probes
          startupProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12
            
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1

          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1

      volumes:
        - name: doctor-storage
          persistentVolumeClaim:
            claimName: doctor-pvc
