apiVersion: apps/v1
kind: Deployment
metadata:
  name: arogyalink-health-institute-deployment
  namespace: arogyalink
spec:
  selector:
    matchLabels:
      app: health-institute
  template:
    metadata:
      labels:
        app: health-institute
    spec:
      containers:
        - name: arogyalink-health-institute
          image: subhamsahadev/arogyalink-health-institute-service:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: 8083
            - containerPort: 5052

          # Environment variables
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: health-institute-configmap
                  key: nodeEnv

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: health-institute-configmap
                  key: dbHost

            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: health-institute-configmap
                  key: dbPort

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: health-institute-secret
                  key: dbUsername

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: health-institute-secret
                  key: dbPassword

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: health-institute-configmap
                  key: dbName

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: health-institute-configmap
                  key: port

            - name: DOCTOR_SERVICE_GRPC_URL
              valueFrom:
                configMapKeyRef:
                  name: health-institute-configmap
                  key: doctorServiceGrpcUrl

            - name: HEALTH_INSTITUTE_SERVICE_GRPC_URL
              valueFrom:
                configMapKeyRef:
                  name: health-institute-configmap
                  key: healthInstituteServiceGrpcUrl

            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: health-institute-secret
                  key: jwtAccessSecret

            - name: JWT_ACCESS_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: health-institute-secret
                  key: jwtAccessExpiresIn

            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: health-institute-secret
                  key: jwtRefreshSecret

            - name: JWT_REFRESH_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: health-institute-secret
                  key: jwtRefreshExpiresIn

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: health-institute-configmap
                  key: redisHost

            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: health-institute-configmap
                  key: redisPort

          # Probes
          startupProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12
            
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1

          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
      #     volumeMounts:
      #       - name: health-institute-storage
      #         mountPath: /usr/src/app/uploads

      # volumes:
      #   - name: health-institute-storage
      #     persistentVolumeClaim:
      #       claimName: health-institute-pvc
