apiVersion: apps/v1
kind: Deployment
metadata:
  name: arogyalink-patient-deployment
  namespace: arogyalink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient

  template:
    metadata:
      name: patient-pod
      namespace: arogyalink
      labels:
        app: patient

    spec:
      containers:
        - name: arogyalink-patient
          image: subhamsahadev/arogyalink-patient-service:1.0.0
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              cpu: 500m
              memory: 1Gi
          ports:
            - containerPort: 8084
            - containerPort: 5053

          # Environment variables
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: patient-configmap
                  key: nodeEnv

            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  name: patient-configmap
                  key: mongodbUrl

            - name: MONGODB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: patient-configmap
                  key: mongodbDatabase

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: patient-configmap
                  key: port

            - name: PATIENT_SERVICE_GRPC_URL
              valueFrom:
                configMapKeyRef:
                  name: patient-configmap
                  key: patientServiceGrpcUrl

            - name: API_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: patient-configmap
                  key: apiBaseUrl

            - name: JWT_ACCESS_SECRET
              valueFrom:
                secretKeyRef:
                  name: patient-secret
                  key: jwtAccessSecret

            - name: JWT_ACCESS_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: patient-secret
                  key: jwtAccessExpiresIn

            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: patient-secret
                  key: jwtRefreshSecret

            - name: JWT_REFRESH_EXPIRES_IN
              valueFrom:
                secretKeyRef:
                  name: patient-secret
                  key: jwtRefreshExpiresIn
            

            - name: JWT_ALGORITHM
              valueFrom:
                configMapKeyRef:
                  name: patient-configmap
                  key: jwtAlgorithm

            - name: REDIS_HOST
              valueFrom:
                configMapKeyRef:
                  name: patient-configmap
                  key: redisHost

            - name: REDIS_PORT
              valueFrom:
                configMapKeyRef:
                  name: patient-configmap
                  key: redisPort
          
          # Volume mount config
          volumeMounts:
            - name: patient-storage
              mountPath: /usr/src/app/uploads
          
          # Probes
          startupProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 12
            
          livenessProbe:
            httpGet:
              path: /
              port: 8081
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1

          readinessProbe:
            httpGet:
              path: /health
              port: 8081
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1

      volumes:
        - name: patient-storage
          persistentVolumeClaim:
            claimName: patient-pvc