from datetime import datetime, timezone

from pymongo import ASCENDING, IndexModel, UpdateOne

from app.db.db_service import get_database


async def up():
    db = get_database()
    states_collection = db["states"]
    districts_collection = db["districts"]

    now = datetime.now(timezone.utc)

    states = [
        {'state_id': 1, 'state_name': 'Andhra Pradesh', 'state_code': 'AP', 'created_at': now},
        {'state_id': 2, 'state_name': 'Arunachal Pradesh', 'state_code': 'AR', 'created_at': now},
        {'state_id': 3, 'state_name': 'Assam', 'state_code': 'AS', 'created_at': now},
        {'state_id': 4, 'state_name': 'Bihar', 'state_code': 'BR', 'created_at': now},
        {'state_id': 5, 'state_name': 'Chhattisgarh', 'state_code': 'CG', 'created_at': now},
        {'state_id': 6, 'state_name': 'Goa', 'state_code': 'GA', 'created_at': now},
        {'state_id': 7, 'state_name': 'Gujarat', 'state_code': 'GJ', 'created_at': now},
        {'state_id': 8, 'state_name': 'Haryana', 'state_code': 'HR', 'created_at': now},
        {'state_id': 9, 'state_name': 'Himachal Pradesh', 'state_code': 'HP', 'created_at': now},
        {'state_id': 10, 'state_name': 'Jharkhand', 'state_code': 'JH', 'created_at': now},
        {'state_id': 11, 'state_name': 'Karnataka', 'state_code': 'KA', 'created_at': now},
        {'state_id': 12, 'state_name': 'Kerala', 'state_code': 'KL', 'created_at': now},
        {'state_id': 13, 'state_name': 'Madhya Pradesh', 'state_code': 'MP', 'created_at': now},
        {'state_id': 14, 'state_name': 'Maharashtra', 'state_code': 'MH', 'created_at': now},
        {'state_id': 15, 'state_name': 'Manipur', 'state_code': 'MN', 'created_at': now},
        {'state_id': 16, 'state_name': 'Meghalaya', 'state_code': 'ML', 'created_at': now},
        {'state_id': 17, 'state_name': 'Mizoram', 'state_code': 'MZ', 'created_at': now},
        {'state_id': 18, 'state_name': 'Nagaland', 'state_code': 'NL', 'created_at': now},
        {'state_id': 19, 'state_name': 'Odisha', 'state_code': 'OD', 'created_at': now},
        {'state_id': 20, 'state_name': 'Punjab', 'state_code': 'PB', 'created_at': now},
        {'state_id': 21, 'state_name': 'Rajasthan', 'state_code': 'RJ', 'created_at': now},
        {'state_id': 22, 'state_name': 'Sikkim', 'state_code': 'SK', 'created_at': now},
        {'state_id': 23, 'state_name': 'Tamil Nadu', 'state_code': 'TN', 'created_at': now},
        {'state_id': 24, 'state_name': 'Telangana', 'state_code': 'TS', 'created_at': now},
        {'state_id': 25, 'state_name': 'Tripura', 'state_code': 'TR', 'created_at': now},
        {'state_id': 26, 'state_name': 'Uttar Pradesh', 'state_code': 'UP', 'created_at': now},
        {'state_id': 27, 'state_name': 'Uttarakhand', 'state_code': 'UK', 'created_at': now},
        {'state_id': 28, 'state_name': 'West Bengal', 'state_code': 'WB', 'created_at': now},
        {'state_id': 29, 'state_name': 'Andaman and Nicobar Islands', 'state_code': 'AN', 'created_at': now},
        {'state_id': 30, 'state_name': 'Chandigarh', 'state_code': 'CH', 'created_at': now},
        {'state_id': 31, 'state_name': 'Dadra and Nagar Haveli and Daman and Diu', 'state_code': 'DH', 'created_at': now},
        {'state_id': 32, 'state_name': 'Delhi', 'state_code': 'DL', 'created_at': now},
        {'state_id': 33, 'state_name': 'Jammu and Kashmir', 'state_code': 'JK', 'created_at': now},
        {'state_id': 34, 'state_name': 'Ladakh', 'state_code': 'LA', 'created_at': now},
        {'state_id': 35, 'state_name': 'Lakshadweep', 'state_code': 'LD', 'created_at': now},
        {'state_id': 36, 'state_name': 'Puducherry', 'state_code': 'PY', 'created_at': now},
    ]

    districts = [
        {'district_id': 1, 'state_id': 1, 'district_name': 'Alluri Sitharama Raju', 'district_code': 'AP-001', 'created_at': now},
        {'district_id': 2, 'state_id': 1, 'district_name': 'Anakapalli', 'district_code': 'AP-002', 'created_at': now},
        {'district_id': 3, 'state_id': 1, 'district_name': 'Ananthapuramu', 'district_code': 'AP-003', 'created_at': now},
        {'district_id': 4, 'state_id': 1, 'district_name': 'Annamayya', 'district_code': 'AP-004', 'created_at': now},
        {'district_id': 5, 'state_id': 1, 'district_name': 'Bapatla', 'district_code': 'AP-005', 'created_at': now},
        {'district_id': 6, 'state_id': 1, 'district_name': 'Chittoor', 'district_code': 'AP-006', 'created_at': now},
        {'district_id': 7, 'state_id': 1, 'district_name': 'Dr. B.R. Ambedkar Konaseema', 'district_code': 'AP-007', 'created_at': now},
        {'district_id': 8, 'state_id': 1, 'district_name': 'East Godavari', 'district_code': 'AP-008', 'created_at': now},
        {'district_id': 9, 'state_id': 1, 'district_name': 'Eluru', 'district_code': 'AP-009', 'created_at': now},
        {'district_id': 10, 'state_id': 1, 'district_name': 'Guntur', 'district_code': 'AP-010', 'created_at': now},
        {'district_id': 11, 'state_id': 1, 'district_name': 'Kakinada', 'district_code': 'AP-011', 'created_at': now},
        {'district_id': 12, 'state_id': 1, 'district_name': 'Krishna', 'district_code': 'AP-012', 'created_at': now},
        {'district_id': 13, 'state_id': 1, 'district_name': 'Kurnool', 'district_code': 'AP-013', 'created_at': now},
        {'district_id': 14, 'state_id': 1, 'district_name': 'Markapuram', 'district_code': 'AP-014', 'created_at': now},
        {'district_id': 15, 'state_id': 1, 'district_name': 'Nandyal', 'district_code': 'AP-015', 'created_at': now},
        {'district_id': 16, 'state_id': 1, 'district_name': 'Ntr', 'district_code': 'AP-016', 'created_at': now},
        {'district_id': 17, 'state_id': 1, 'district_name': 'Palnadu', 'district_code': 'AP-017', 'created_at': now},
        {'district_id': 18, 'state_id': 1, 'district_name': 'Parvathipuram Manyam', 'district_code': 'AP-018', 'created_at': now},
        {'district_id': 19, 'state_id': 1, 'district_name': 'Polavaram', 'district_code': 'AP-019', 'created_at': now},
        {'district_id': 20, 'state_id': 1, 'district_name': 'Prakasam', 'district_code': 'AP-020', 'created_at': now},
        {'district_id': 21, 'state_id': 1, 'district_name': 'Sri Potti Sriramulu Nellore', 'district_code': 'AP-021', 'created_at': now},
        {'district_id': 22, 'state_id': 1, 'district_name': 'Sri Sathya Sai', 'district_code': 'AP-022', 'created_at': now},
        {'district_id': 23, 'state_id': 1, 'district_name': 'Srikakulam', 'district_code': 'AP-023', 'created_at': now},
        {'district_id': 24, 'state_id': 1, 'district_name': 'Tirupati', 'district_code': 'AP-024', 'created_at': now},
        {'district_id': 25, 'state_id': 1, 'district_name': 'Visakhapatnam', 'district_code': 'AP-025', 'created_at': now},
        {'district_id': 26, 'state_id': 1, 'district_name': 'Vizianagaram', 'district_code': 'AP-026', 'created_at': now},
        {'district_id': 27, 'state_id': 1, 'district_name': 'West Godavari', 'district_code': 'AP-027', 'created_at': now},
        {'district_id': 28, 'state_id': 1, 'district_name': 'YSR Kadapa', 'district_code': 'AP-028', 'created_at': now},
        {'district_id': 29, 'state_id': 2, 'district_name': 'Anjaw', 'district_code': 'AR-001', 'created_at': now},
        {'district_id': 30, 'state_id': 2, 'district_name': 'Bichom', 'district_code': 'AR-002', 'created_at': now},
        {'district_id': 31, 'state_id': 2, 'district_name': 'Changlang', 'district_code': 'AR-003', 'created_at': now},
        {'district_id': 32, 'state_id': 2, 'district_name': 'Dibang Valley', 'district_code': 'AR-004', 'created_at': now},
        {'district_id': 33, 'state_id': 2, 'district_name': 'East Kameng', 'district_code': 'AR-005', 'created_at': now},
        {'district_id': 34, 'state_id': 2, 'district_name': 'East Siang', 'district_code': 'AR-006', 'created_at': now},
        {'district_id': 35, 'state_id': 2, 'district_name': 'Kamle', 'district_code': 'AR-007', 'created_at': now},
        {'district_id': 36, 'state_id': 2, 'district_name': 'Keyi Panyor', 'district_code': 'AR-008', 'created_at': now},
        {'district_id': 37, 'state_id': 2, 'district_name': 'Kra Daadi', 'district_code': 'AR-009', 'created_at': now},
        {'district_id': 38, 'state_id': 2, 'district_name': 'Kurung Kumey', 'district_code': 'AR-010', 'created_at': now},
        {'district_id': 39, 'state_id': 2, 'district_name': 'Leparada', 'district_code': 'AR-011', 'created_at': now},
        {'district_id': 40, 'state_id': 2, 'district_name': 'Lohit', 'district_code': 'AR-012', 'created_at': now},
        {'district_id': 41, 'state_id': 2, 'district_name': 'Longding', 'district_code': 'AR-013', 'created_at': now},
        {'district_id': 42, 'state_id': 2, 'district_name': 'Lower Dibang Valley', 'district_code': 'AR-014', 'created_at': now},
        {'district_id': 43, 'state_id': 2, 'district_name': 'Lower Siang', 'district_code': 'AR-015', 'created_at': now},
        {'district_id': 44, 'state_id': 2, 'district_name': 'Lower Subansiri', 'district_code': 'AR-016', 'created_at': now},
        {'district_id': 45, 'state_id': 2, 'district_name': 'Namsai', 'district_code': 'AR-017', 'created_at': now},
        {'district_id': 46, 'state_id': 2, 'district_name': 'Pakke Kessang', 'district_code': 'AR-018', 'created_at': now},
        {'district_id': 47, 'state_id': 2, 'district_name': 'Papum Pare', 'district_code': 'AR-019', 'created_at': now},
        {'district_id': 48, 'state_id': 2, 'district_name': 'Shi Yomi', 'district_code': 'AR-020', 'created_at': now},
        {'district_id': 49, 'state_id': 2, 'district_name': 'Siang', 'district_code': 'AR-021', 'created_at': now},
        {'district_id': 50, 'state_id': 2, 'district_name': 'Tawang', 'district_code': 'AR-022', 'created_at': now},
        {'district_id': 51, 'state_id': 2, 'district_name': 'Tirap', 'district_code': 'AR-023', 'created_at': now},
        {'district_id': 52, 'state_id': 2, 'district_name': 'Upper Siang', 'district_code': 'AR-024', 'created_at': now},
        {'district_id': 53, 'state_id': 2, 'district_name': 'Upper Subansiri', 'district_code': 'AR-025', 'created_at': now},
        {'district_id': 54, 'state_id': 2, 'district_name': 'West Kameng', 'district_code': 'AR-026', 'created_at': now},
        {'district_id': 55, 'state_id': 2, 'district_name': 'West Siang', 'district_code': 'AR-027', 'created_at': now},
        {'district_id': 56, 'state_id': 3, 'district_name': 'Bajali', 'district_code': 'AS-001', 'created_at': now},
        {'district_id': 57, 'state_id': 3, 'district_name': 'Baksa', 'district_code': 'AS-002', 'created_at': now},
        {'district_id': 58, 'state_id': 3, 'district_name': 'Barpeta', 'district_code': 'AS-003', 'created_at': now},
        {'district_id': 59, 'state_id': 3, 'district_name': 'Biswanath', 'district_code': 'AS-004', 'created_at': now},
        {'district_id': 60, 'state_id': 3, 'district_name': 'Bongaigaon', 'district_code': 'AS-005', 'created_at': now},
        {'district_id': 61, 'state_id': 3, 'district_name': 'Cachar', 'district_code': 'AS-006', 'created_at': now},
        {'district_id': 62, 'state_id': 3, 'district_name': 'Charaideo', 'district_code': 'AS-007', 'created_at': now},
        {'district_id': 63, 'state_id': 3, 'district_name': 'Chirang', 'district_code': 'AS-008', 'created_at': now},
        {'district_id': 64, 'state_id': 3, 'district_name': 'Darrang', 'district_code': 'AS-009', 'created_at': now},
        {'district_id': 65, 'state_id': 3, 'district_name': 'Dhemaji', 'district_code': 'AS-010', 'created_at': now},
        {'district_id': 66, 'state_id': 3, 'district_name': 'Dhubri', 'district_code': 'AS-011', 'created_at': now},
        {'district_id': 67, 'state_id': 3, 'district_name': 'Dibrugarh', 'district_code': 'AS-012', 'created_at': now},
        {'district_id': 68, 'state_id': 3, 'district_name': 'Dima Hasao', 'district_code': 'AS-013', 'created_at': now},
        {'district_id': 69, 'state_id': 3, 'district_name': 'Goalpara', 'district_code': 'AS-014', 'created_at': now},
        {'district_id': 70, 'state_id': 3, 'district_name': 'Golaghat', 'district_code': 'AS-015', 'created_at': now},
        {'district_id': 71, 'state_id': 3, 'district_name': 'Hailakandi', 'district_code': 'AS-016', 'created_at': now},
        {'district_id': 72, 'state_id': 3, 'district_name': 'Hojai', 'district_code': 'AS-017', 'created_at': now},
        {'district_id': 73, 'state_id': 3, 'district_name': 'Jorhat', 'district_code': 'AS-018', 'created_at': now},
        {'district_id': 74, 'state_id': 3, 'district_name': 'Kamrup', 'district_code': 'AS-019', 'created_at': now},
        {'district_id': 75, 'state_id': 3, 'district_name': 'Kamrup Metropolitan', 'district_code': 'AS-020', 'created_at': now},
        {'district_id': 76, 'state_id': 3, 'district_name': 'Karbi Anglong', 'district_code': 'AS-021', 'created_at': now},
        {'district_id': 77, 'state_id': 3, 'district_name': 'Kokrajhar', 'district_code': 'AS-022', 'created_at': now},
        {'district_id': 78, 'state_id': 3, 'district_name': 'Lakhimpur', 'district_code': 'AS-023', 'created_at': now},
        {'district_id': 79, 'state_id': 3, 'district_name': 'Majuli', 'district_code': 'AS-024', 'created_at': now},
        {'district_id': 80, 'state_id': 3, 'district_name': 'Morigaon', 'district_code': 'AS-025', 'created_at': now},
        {'district_id': 81, 'state_id': 3, 'district_name': 'Nagaon', 'district_code': 'AS-026', 'created_at': now},
        {'district_id': 82, 'state_id': 3, 'district_name': 'Nalbari', 'district_code': 'AS-027', 'created_at': now},
        {'district_id': 83, 'state_id': 3, 'district_name': 'Sivasagar', 'district_code': 'AS-028', 'created_at': now},
        {'district_id': 84, 'state_id': 3, 'district_name': 'Sonitpur', 'district_code': 'AS-029', 'created_at': now},
        {'district_id': 85, 'state_id': 3, 'district_name': 'South Salmara-Mankachar', 'district_code': 'AS-030', 'created_at': now},
        {'district_id': 86, 'state_id': 3, 'district_name': 'Tinsukia', 'district_code': 'AS-031', 'created_at': now},
        {'district_id': 87, 'state_id': 3, 'district_name': 'Udalguri', 'district_code': 'AS-032', 'created_at': now},
        {'district_id': 88, 'state_id': 3, 'district_name': 'West Karbi Anglong', 'district_code': 'AS-033', 'created_at': now},
        {'district_id': 89, 'state_id': 3, 'district_name': 'Tamulpur', 'district_code': 'AS-034', 'created_at': now},
        {'district_id': 90, 'state_id': 3, 'district_name': 'Sribhumi', 'district_code': 'AS-035', 'created_at': now},
        {'district_id': 91, 'state_id': 4, 'district_name': 'Araria', 'district_code': 'BR-001', 'created_at': now},
        {'district_id': 92, 'state_id': 4, 'district_name': 'Arwal', 'district_code': 'BR-002', 'created_at': now},
        {'district_id': 93, 'state_id': 4, 'district_name': 'Aurangabad', 'district_code': 'BR-003', 'created_at': now},
        {'district_id': 94, 'state_id': 4, 'district_name': 'Banka', 'district_code': 'BR-004', 'created_at': now},
        {'district_id': 95, 'state_id': 4, 'district_name': 'Begusarai', 'district_code': 'BR-005', 'created_at': now},
        {'district_id': 96, 'state_id': 4, 'district_name': 'Bhagalpur', 'district_code': 'BR-006', 'created_at': now},
        {'district_id': 97, 'state_id': 4, 'district_name': 'Bhojpur', 'district_code': 'BR-007', 'created_at': now},
        {'district_id': 98, 'state_id': 4, 'district_name': 'Buxar', 'district_code': 'BR-008', 'created_at': now},
        {'district_id': 99, 'state_id': 4, 'district_name': 'Darbhanga', 'district_code': 'BR-009', 'created_at': now},
        {'district_id': 100, 'state_id': 4, 'district_name': 'Gaya', 'district_code': 'BR-010', 'created_at': now},
        {'district_id': 101, 'state_id': 4, 'district_name': 'Gopalganj', 'district_code': 'BR-011', 'created_at': now},
        {'district_id': 102, 'state_id': 4, 'district_name': 'Jamui', 'district_code': 'BR-012', 'created_at': now},
        {'district_id': 103, 'state_id': 4, 'district_name': 'Jehanabad', 'district_code': 'BR-013', 'created_at': now},
        {'district_id': 104, 'state_id': 4, 'district_name': 'Kaimur (Bhabua)', 'district_code': 'BR-014', 'created_at': now},
        {'district_id': 105, 'state_id': 4, 'district_name': 'Katihar', 'district_code': 'BR-015', 'created_at': now},
        {'district_id': 106, 'state_id': 4, 'district_name': 'Khagaria', 'district_code': 'BR-016', 'created_at': now},
        {'district_id': 107, 'state_id': 4, 'district_name': 'Kishanganj', 'district_code': 'BR-017', 'created_at': now},
        {'district_id': 108, 'state_id': 4, 'district_name': 'Lakhisarai', 'district_code': 'BR-018', 'created_at': now},
        {'district_id': 109, 'state_id': 4, 'district_name': 'Madhepura', 'district_code': 'BR-019', 'created_at': now},
        {'district_id': 110, 'state_id': 4, 'district_name': 'Madhubani', 'district_code': 'BR-020', 'created_at': now},
        {'district_id': 111, 'state_id': 4, 'district_name': 'Munger', 'district_code': 'BR-021', 'created_at': now},
        {'district_id': 112, 'state_id': 4, 'district_name': 'Muzaffarpur', 'district_code': 'BR-022', 'created_at': now},
        {'district_id': 113, 'state_id': 4, 'district_name': 'Nalanda', 'district_code': 'BR-023', 'created_at': now},
        {'district_id': 114, 'state_id': 4, 'district_name': 'Nawada', 'district_code': 'BR-024', 'created_at': now},
        {'district_id': 115, 'state_id': 4, 'district_name': 'Pashchim Champaran', 'district_code': 'BR-025', 'created_at': now},
        {'district_id': 116, 'state_id': 4, 'district_name': 'Purba Champaran', 'district_code': 'BR-026', 'created_at': now},
        {'district_id': 117, 'state_id': 4, 'district_name': 'Patna', 'district_code': 'BR-027', 'created_at': now},
        {'district_id': 118, 'state_id': 4, 'district_name': 'Purnia', 'district_code': 'BR-028', 'created_at': now},
        {'district_id': 119, 'state_id': 4, 'district_name': 'Rohtas', 'district_code': 'BR-029', 'created_at': now},
        {'district_id': 120, 'state_id': 4, 'district_name': 'Saharsa', 'district_code': 'BR-030', 'created_at': now},
        {'district_id': 121, 'state_id': 4, 'district_name': 'Samastipur', 'district_code': 'BR-031', 'created_at': now},
        {'district_id': 122, 'state_id': 4, 'district_name': 'Saran', 'district_code': 'BR-032', 'created_at': now},
        {'district_id': 123, 'state_id': 4, 'district_name': 'Sheikhpura', 'district_code': 'BR-033', 'created_at': now},
        {'district_id': 124, 'state_id': 4, 'district_name': 'Sheohar', 'district_code': 'BR-034', 'created_at': now},
        {'district_id': 125, 'state_id': 4, 'district_name': 'Sitamarhi', 'district_code': 'BR-035', 'created_at': now},
        {'district_id': 126, 'state_id': 4, 'district_name': 'Siwan', 'district_code': 'BR-036', 'created_at': now},
        {'district_id': 127, 'state_id': 4, 'district_name': 'Supaul', 'district_code': 'BR-037', 'created_at': now},
        {'district_id': 128, 'state_id': 4, 'district_name': 'Vaishali', 'district_code': 'BR-038', 'created_at': now},
        {'district_id': 129, 'state_id': 5, 'district_name': 'Balod', 'district_code': 'CG-001', 'created_at': now},
        {'district_id': 130, 'state_id': 5, 'district_name': 'Balodabazar-Bhatapara', 'district_code': 'CG-002', 'created_at': now},
        {'district_id': 131, 'state_id': 5, 'district_name': 'Balrampur-Ramanujganj', 'district_code': 'CG-003', 'created_at': now},
        {'district_id': 132, 'state_id': 5, 'district_name': 'Bastar', 'district_code': 'CG-004', 'created_at': now},
        {'district_id': 133, 'state_id': 5, 'district_name': 'Bemetara', 'district_code': 'CG-005', 'created_at': now},
        {'district_id': 134, 'state_id': 5, 'district_name': 'Bijapur', 'district_code': 'CG-006', 'created_at': now},
        {'district_id': 135, 'state_id': 5, 'district_name': 'Bilaspur', 'district_code': 'CG-007', 'created_at': now},
        {'district_id': 136, 'state_id': 5, 'district_name': 'Dakshin Bastar Dantewada', 'district_code': 'CG-008', 'created_at': now},
        {'district_id': 137, 'state_id': 5, 'district_name': 'Dhamtari', 'district_code': 'CG-009', 'created_at': now},
        {'district_id': 138, 'state_id': 5, 'district_name': 'Durg', 'district_code': 'CG-010', 'created_at': now},
        {'district_id': 139, 'state_id': 5, 'district_name': 'Gariyaband', 'district_code': 'CG-011', 'created_at': now},
        {'district_id': 140, 'state_id': 5, 'district_name': 'Gaurela-Pendra-Marwahi', 'district_code': 'CG-012', 'created_at': now},
        {'district_id': 141, 'state_id': 5, 'district_name': 'Janjgir-Champa', 'district_code': 'CG-013', 'created_at': now},
        {'district_id': 142, 'state_id': 5, 'district_name': 'Jashpur', 'district_code': 'CG-014', 'created_at': now},
        {'district_id': 143, 'state_id': 5, 'district_name': 'Kabeerdham', 'district_code': 'CG-015', 'created_at': now},
        {'district_id': 144, 'state_id': 5, 'district_name': 'Khairagarh-Chhuikhadan-Gandai', 'district_code': 'CG-016', 'created_at': now},
        {'district_id': 145, 'state_id': 5, 'district_name': 'Kondagaon', 'district_code': 'CG-017', 'created_at': now},
        {'district_id': 146, 'state_id': 5, 'district_name': 'Korba', 'district_code': 'CG-018', 'created_at': now},
        {'district_id': 147, 'state_id': 5, 'district_name': 'Korea', 'district_code': 'CG-019', 'created_at': now},
        {'district_id': 148, 'state_id': 5, 'district_name': 'Mahasamund', 'district_code': 'CG-020', 'created_at': now},
        {'district_id': 149, 'state_id': 5, 'district_name': 'Manendragarh-Chirmiri-Bharatpur(M C B)', 'district_code': 'CG-021', 'created_at': now},
        {'district_id': 150, 'state_id': 5, 'district_name': 'Mohla-Manpur-Ambagarh Chouki', 'district_code': 'CG-022', 'created_at': now},
        {'district_id': 151, 'state_id': 5, 'district_name': 'Mungeli', 'district_code': 'CG-023', 'created_at': now},
        {'district_id': 152, 'state_id': 5, 'district_name': 'Narayanpur', 'district_code': 'CG-024', 'created_at': now},
        {'district_id': 153, 'state_id': 5, 'district_name': 'Raigarh', 'district_code': 'CG-025', 'created_at': now},
        {'district_id': 154, 'state_id': 5, 'district_name': 'Raipur', 'district_code': 'CG-026', 'created_at': now},
        {'district_id': 155, 'state_id': 5, 'district_name': 'Rajnandgaon', 'district_code': 'CG-027', 'created_at': now},
        {'district_id': 156, 'state_id': 5, 'district_name': 'Sakti', 'district_code': 'CG-028', 'created_at': now},
        {'district_id': 157, 'state_id': 5, 'district_name': 'Sarangarh-Bilaigarh', 'district_code': 'CG-029', 'created_at': now},
        {'district_id': 158, 'state_id': 5, 'district_name': 'Sukma', 'district_code': 'CG-030', 'created_at': now},
        {'district_id': 159, 'state_id': 5, 'district_name': 'Surajpur', 'district_code': 'CG-031', 'created_at': now},
        {'district_id': 160, 'state_id': 5, 'district_name': 'Surguja', 'district_code': 'CG-032', 'created_at': now},
        {'district_id': 161, 'state_id': 5, 'district_name': 'Kabirdham', 'district_code': 'CG-033', 'created_at': now},
        {'district_id': 162, 'state_id': 6, 'district_name': 'Kushavati', 'district_code': 'GA-001', 'created_at': now},
        {'district_id': 163, 'state_id': 6, 'district_name': 'North Goa', 'district_code': 'GA-002', 'created_at': now},
        {'district_id': 164, 'state_id': 6, 'district_name': 'South Goa', 'district_code': 'GA-003', 'created_at': now},
        {'district_id': 165, 'state_id': 7, 'district_name': 'Ahmedabad', 'district_code': 'GJ-001', 'created_at': now},
        {'district_id': 166, 'state_id': 7, 'district_name': 'Amreli', 'district_code': 'GJ-002', 'created_at': now},
        {'district_id': 167, 'state_id': 7, 'district_name': 'Anand', 'district_code': 'GJ-003', 'created_at': now},
        {'district_id': 168, 'state_id': 7, 'district_name': 'Arvalli', 'district_code': 'GJ-004', 'created_at': now},
        {'district_id': 169, 'state_id': 7, 'district_name': 'Banas Kantha', 'district_code': 'GJ-005', 'created_at': now},
        {'district_id': 170, 'state_id': 7, 'district_name': 'Bharuch', 'district_code': 'GJ-006', 'created_at': now},
        {'district_id': 171, 'state_id': 7, 'district_name': 'Bhavnagar', 'district_code': 'GJ-007', 'created_at': now},
        {'district_id': 172, 'state_id': 7, 'district_name': 'Botad', 'district_code': 'GJ-008', 'created_at': now},
        {'district_id': 173, 'state_id': 7, 'district_name': 'Chhotaudepur', 'district_code': 'GJ-009', 'created_at': now},
        {'district_id': 174, 'state_id': 7, 'district_name': 'Dahod', 'district_code': 'GJ-010', 'created_at': now},
        {'district_id': 175, 'state_id': 7, 'district_name': 'Dangs', 'district_code': 'GJ-011', 'created_at': now},
        {'district_id': 176, 'state_id': 7, 'district_name': 'Devbhumi Dwarka', 'district_code': 'GJ-012', 'created_at': now},
        {'district_id': 177, 'state_id': 7, 'district_name': 'Gandhinagar', 'district_code': 'GJ-013', 'created_at': now},
        {'district_id': 178, 'state_id': 7, 'district_name': 'Gir Somnath', 'district_code': 'GJ-014', 'created_at': now},
        {'district_id': 179, 'state_id': 7, 'district_name': 'Jamnagar', 'district_code': 'GJ-015', 'created_at': now},
        {'district_id': 180, 'state_id': 7, 'district_name': 'Junagadh', 'district_code': 'GJ-016', 'created_at': now},
        {'district_id': 181, 'state_id': 7, 'district_name': 'Kachchh', 'district_code': 'GJ-017', 'created_at': now},
        {'district_id': 182, 'state_id': 7, 'district_name': 'Kheda', 'district_code': 'GJ-018', 'created_at': now},
        {'district_id': 183, 'state_id': 7, 'district_name': 'Mahesana', 'district_code': 'GJ-019', 'created_at': now},
        {'district_id': 184, 'state_id': 7, 'district_name': 'Mahisagar', 'district_code': 'GJ-020', 'created_at': now},
        {'district_id': 185, 'state_id': 7, 'district_name': 'Morbi', 'district_code': 'GJ-021', 'created_at': now},
        {'district_id': 186, 'state_id': 7, 'district_name': 'Narmada', 'district_code': 'GJ-022', 'created_at': now},
        {'district_id': 187, 'state_id': 7, 'district_name': 'Navsari', 'district_code': 'GJ-023', 'created_at': now},
        {'district_id': 188, 'state_id': 7, 'district_name': 'Panch Mahals', 'district_code': 'GJ-024', 'created_at': now},
        {'district_id': 189, 'state_id': 7, 'district_name': 'Patan', 'district_code': 'GJ-025', 'created_at': now},
        {'district_id': 190, 'state_id': 7, 'district_name': 'Porbandar', 'district_code': 'GJ-026', 'created_at': now},
        {'district_id': 191, 'state_id': 7, 'district_name': 'Rajkot', 'district_code': 'GJ-027', 'created_at': now},
        {'district_id': 192, 'state_id': 7, 'district_name': 'Sabarkantha', 'district_code': 'GJ-028', 'created_at': now},
        {'district_id': 193, 'state_id': 7, 'district_name': 'Surat', 'district_code': 'GJ-029', 'created_at': now},
        {'district_id': 194, 'state_id': 7, 'district_name': 'Surendranagar', 'district_code': 'GJ-030', 'created_at': now},
        {'district_id': 195, 'state_id': 7, 'district_name': 'Tapi', 'district_code': 'GJ-031', 'created_at': now},
        {'district_id': 196, 'state_id': 7, 'district_name': 'Vadodara', 'district_code': 'GJ-032', 'created_at': now},
        {'district_id': 197, 'state_id': 7, 'district_name': 'Valsad', 'district_code': 'GJ-033', 'created_at': now},
        {'district_id': 198, 'state_id': 7, 'district_name': 'Vav-Tharad', 'district_code': 'GJ-034', 'created_at': now},
        {'district_id': 199, 'state_id': 8, 'district_name': 'Ambala', 'district_code': 'HR-001', 'created_at': now},
        {'district_id': 200, 'state_id': 8, 'district_name': 'Bhiwani', 'district_code': 'HR-002', 'created_at': now},
        {'district_id': 201, 'state_id': 8, 'district_name': 'Charkhi Dadri', 'district_code': 'HR-003', 'created_at': now},
        {'district_id': 202, 'state_id': 8, 'district_name': 'Faridabad', 'district_code': 'HR-004', 'created_at': now},
        {'district_id': 203, 'state_id': 8, 'district_name': 'Fatehabad', 'district_code': 'HR-005', 'created_at': now},
        {'district_id': 204, 'state_id': 8, 'district_name': 'Gurugram', 'district_code': 'HR-006', 'created_at': now},
        {'district_id': 205, 'state_id': 8, 'district_name': 'Hansi', 'district_code': 'HR-007', 'created_at': now},
        {'district_id': 206, 'state_id': 8, 'district_name': 'Hisar', 'district_code': 'HR-008', 'created_at': now},
        {'district_id': 207, 'state_id': 8, 'district_name': 'Jhajjar', 'district_code': 'HR-009', 'created_at': now},
        {'district_id': 208, 'state_id': 8, 'district_name': 'Jind', 'district_code': 'HR-010', 'created_at': now},
        {'district_id': 209, 'state_id': 8, 'district_name': 'Kaithal', 'district_code': 'HR-011', 'created_at': now},
        {'district_id': 210, 'state_id': 8, 'district_name': 'Karnal', 'district_code': 'HR-012', 'created_at': now},
        {'district_id': 211, 'state_id': 8, 'district_name': 'Kurukshetra', 'district_code': 'HR-013', 'created_at': now},
        {'district_id': 212, 'state_id': 8, 'district_name': 'Mahendragarh', 'district_code': 'HR-014', 'created_at': now},
        {'district_id': 213, 'state_id': 8, 'district_name': 'Nuh', 'district_code': 'HR-015', 'created_at': now},
        {'district_id': 214, 'state_id': 8, 'district_name': 'Palwal', 'district_code': 'HR-016', 'created_at': now},
        {'district_id': 215, 'state_id': 8, 'district_name': 'Panchkula', 'district_code': 'HR-017', 'created_at': now},
        {'district_id': 216, 'state_id': 8, 'district_name': 'Panipat', 'district_code': 'HR-018', 'created_at': now},
        {'district_id': 217, 'state_id': 8, 'district_name': 'Rewari', 'district_code': 'HR-019', 'created_at': now},
        {'district_id': 218, 'state_id': 8, 'district_name': 'Rohtak', 'district_code': 'HR-020', 'created_at': now},
        {'district_id': 219, 'state_id': 8, 'district_name': 'Sirsa', 'district_code': 'HR-021', 'created_at': now},
        {'district_id': 220, 'state_id': 8, 'district_name': 'Sonipat', 'district_code': 'HR-022', 'created_at': now},
        {'district_id': 221, 'state_id': 8, 'district_name': 'Yamunanagar', 'district_code': 'HR-023', 'created_at': now},
        {'district_id': 222, 'state_id': 9, 'district_name': 'Bilaspur', 'district_code': 'HP-001', 'created_at': now},
        {'district_id': 223, 'state_id': 9, 'district_name': 'Chamba', 'district_code': 'HP-002', 'created_at': now},
        {'district_id': 224, 'state_id': 9, 'district_name': 'Hamirpur', 'district_code': 'HP-003', 'created_at': now},
        {'district_id': 225, 'state_id': 9, 'district_name': 'Kangra', 'district_code': 'HP-004', 'created_at': now},
        {'district_id': 226, 'state_id': 9, 'district_name': 'Kinnaur', 'district_code': 'HP-005', 'created_at': now},
        {'district_id': 227, 'state_id': 9, 'district_name': 'Kullu', 'district_code': 'HP-006', 'created_at': now},
        {'district_id': 228, 'state_id': 9, 'district_name': 'Lahaul And Spiti', 'district_code': 'HP-007', 'created_at': now},
        {'district_id': 229, 'state_id': 9, 'district_name': 'Mandi', 'district_code': 'HP-008', 'created_at': now},
        {'district_id': 230, 'state_id': 9, 'district_name': 'Shimla', 'district_code': 'HP-009', 'created_at': now},
        {'district_id': 231, 'state_id': 9, 'district_name': 'Sirmaur', 'district_code': 'HP-010', 'created_at': now},
        {'district_id': 232, 'state_id': 9, 'district_name': 'Solan', 'district_code': 'HP-011', 'created_at': now},
        {'district_id': 233, 'state_id': 9, 'district_name': 'Una', 'district_code': 'HP-012', 'created_at': now},
        {'district_id': 234, 'state_id': 10, 'district_name': 'Bokaro', 'district_code': 'JH-001', 'created_at': now},
        {'district_id': 235, 'state_id': 10, 'district_name': 'Chatra', 'district_code': 'JH-002', 'created_at': now},
        {'district_id': 236, 'state_id': 10, 'district_name': 'Deoghar', 'district_code': 'JH-003', 'created_at': now},
        {'district_id': 237, 'state_id': 10, 'district_name': 'Dhanbad', 'district_code': 'JH-004', 'created_at': now},
        {'district_id': 238, 'state_id': 10, 'district_name': 'Dumka', 'district_code': 'JH-005', 'created_at': now},
        {'district_id': 239, 'state_id': 10, 'district_name': 'East Singhbum', 'district_code': 'JH-006', 'created_at': now},
        {'district_id': 240, 'state_id': 10, 'district_name': 'Garhwa', 'district_code': 'JH-007', 'created_at': now},
        {'district_id': 241, 'state_id': 10, 'district_name': 'Giridih', 'district_code': 'JH-008', 'created_at': now},
        {'district_id': 242, 'state_id': 10, 'district_name': 'Godda', 'district_code': 'JH-009', 'created_at': now},
        {'district_id': 243, 'state_id': 10, 'district_name': 'Gumla', 'district_code': 'JH-010', 'created_at': now},
        {'district_id': 244, 'state_id': 10, 'district_name': 'Hazaribagh', 'district_code': 'JH-011', 'created_at': now},
        {'district_id': 245, 'state_id': 10, 'district_name': 'Jamtara', 'district_code': 'JH-012', 'created_at': now},
        {'district_id': 246, 'state_id': 10, 'district_name': 'Khunti', 'district_code': 'JH-013', 'created_at': now},
        {'district_id': 247, 'state_id': 10, 'district_name': 'Koderma', 'district_code': 'JH-014', 'created_at': now},
        {'district_id': 248, 'state_id': 10, 'district_name': 'Latehar', 'district_code': 'JH-015', 'created_at': now},
        {'district_id': 249, 'state_id': 10, 'district_name': 'Lohardaga', 'district_code': 'JH-016', 'created_at': now},
        {'district_id': 250, 'state_id': 10, 'district_name': 'Pakur', 'district_code': 'JH-017', 'created_at': now},
        {'district_id': 251, 'state_id': 10, 'district_name': 'Palamu', 'district_code': 'JH-018', 'created_at': now},
        {'district_id': 252, 'state_id': 10, 'district_name': 'Ramgarh', 'district_code': 'JH-019', 'created_at': now},
        {'district_id': 253, 'state_id': 10, 'district_name': 'Ranchi', 'district_code': 'JH-020', 'created_at': now},
        {'district_id': 254, 'state_id': 10, 'district_name': 'Sahebganj', 'district_code': 'JH-021', 'created_at': now},
        {'district_id': 255, 'state_id': 10, 'district_name': 'Saraikela Kharsawan', 'district_code': 'JH-022', 'created_at': now},
        {'district_id': 256, 'state_id': 10, 'district_name': 'Simdega', 'district_code': 'JH-023', 'created_at': now},
        {'district_id': 257, 'state_id': 10, 'district_name': 'West Singhbhum', 'district_code': 'JH-024', 'created_at': now},
        {'district_id': 258, 'state_id': 11, 'district_name': 'Bagalkote', 'district_code': 'KA-001', 'created_at': now},
        {'district_id': 259, 'state_id': 11, 'district_name': 'Ballari', 'district_code': 'KA-002', 'created_at': now},
        {'district_id': 260, 'state_id': 11, 'district_name': 'Belagavi', 'district_code': 'KA-003', 'created_at': now},
        {'district_id': 261, 'state_id': 11, 'district_name': 'Bengaluru Rural', 'district_code': 'KA-004', 'created_at': now},
        {'district_id': 262, 'state_id': 11, 'district_name': 'Bengaluru South', 'district_code': 'KA-005', 'created_at': now},
        {'district_id': 263, 'state_id': 11, 'district_name': 'Bengaluru Urban', 'district_code': 'KA-006', 'created_at': now},
        {'district_id': 264, 'state_id': 11, 'district_name': 'Bidar', 'district_code': 'KA-007', 'created_at': now},
        {'district_id': 265, 'state_id': 11, 'district_name': 'Chamarajanagar', 'district_code': 'KA-008', 'created_at': now},
        {'district_id': 266, 'state_id': 11, 'district_name': 'Chikkaballapura', 'district_code': 'KA-009', 'created_at': now},
        {'district_id': 267, 'state_id': 11, 'district_name': 'Chikkamagaluru', 'district_code': 'KA-010', 'created_at': now},
        {'district_id': 268, 'state_id': 11, 'district_name': 'Chitradurga', 'district_code': 'KA-011', 'created_at': now},
        {'district_id': 269, 'state_id': 11, 'district_name': 'Dakshina Kannada', 'district_code': 'KA-012', 'created_at': now},
        {'district_id': 270, 'state_id': 11, 'district_name': 'Davanagere', 'district_code': 'KA-013', 'created_at': now},
        {'district_id': 271, 'state_id': 11, 'district_name': 'Dharwad', 'district_code': 'KA-014', 'created_at': now},
        {'district_id': 272, 'state_id': 11, 'district_name': 'Gadag', 'district_code': 'KA-015', 'created_at': now},
        {'district_id': 273, 'state_id': 11, 'district_name': 'Hassan', 'district_code': 'KA-016', 'created_at': now},
        {'district_id': 274, 'state_id': 11, 'district_name': 'Haveri', 'district_code': 'KA-017', 'created_at': now},
        {'district_id': 275, 'state_id': 11, 'district_name': 'Kalaburagi', 'district_code': 'KA-018', 'created_at': now},
        {'district_id': 276, 'state_id': 11, 'district_name': 'Kodagu', 'district_code': 'KA-019', 'created_at': now},
        {'district_id': 277, 'state_id': 11, 'district_name': 'Kolar', 'district_code': 'KA-020', 'created_at': now},
        {'district_id': 278, 'state_id': 11, 'district_name': 'Koppal', 'district_code': 'KA-021', 'created_at': now},
        {'district_id': 279, 'state_id': 11, 'district_name': 'Mandya', 'district_code': 'KA-022', 'created_at': now},
        {'district_id': 280, 'state_id': 11, 'district_name': 'Mysuru', 'district_code': 'KA-023', 'created_at': now},
        {'district_id': 281, 'state_id': 11, 'district_name': 'Raichur', 'district_code': 'KA-024', 'created_at': now},
        {'district_id': 282, 'state_id': 11, 'district_name': 'Shivamogga', 'district_code': 'KA-025', 'created_at': now},
        {'district_id': 283, 'state_id': 11, 'district_name': 'Tumakuru', 'district_code': 'KA-026', 'created_at': now},
        {'district_id': 284, 'state_id': 11, 'district_name': 'Udupi', 'district_code': 'KA-027', 'created_at': now},
        {'district_id': 285, 'state_id': 11, 'district_name': 'Uttara Kannada', 'district_code': 'KA-028', 'created_at': now},
        {'district_id': 286, 'state_id': 11, 'district_name': 'Vijayapura', 'district_code': 'KA-029', 'created_at': now},
        {'district_id': 287, 'state_id': 11, 'district_name': 'Yadgir', 'district_code': 'KA-030', 'created_at': now},
        {'district_id': 288, 'state_id': 11, 'district_name': 'Vijayanagara', 'district_code': 'KA-031', 'created_at': now},
        {'district_id': 289, 'state_id': 12, 'district_name': 'Alappuzha', 'district_code': 'KL-001', 'created_at': now},
        {'district_id': 290, 'state_id': 12, 'district_name': 'Ernakulam', 'district_code': 'KL-002', 'created_at': now},
        {'district_id': 291, 'state_id': 12, 'district_name': 'Idukki', 'district_code': 'KL-003', 'created_at': now},
        {'district_id': 292, 'state_id': 12, 'district_name': 'Kannur', 'district_code': 'KL-004', 'created_at': now},
        {'district_id': 293, 'state_id': 12, 'district_name': 'Kasaragod', 'district_code': 'KL-005', 'created_at': now},
        {'district_id': 294, 'state_id': 12, 'district_name': 'Kollam', 'district_code': 'KL-006', 'created_at': now},
        {'district_id': 295, 'state_id': 12, 'district_name': 'Kottayam', 'district_code': 'KL-007', 'created_at': now},
        {'district_id': 296, 'state_id': 12, 'district_name': 'Kozhikode', 'district_code': 'KL-008', 'created_at': now},
        {'district_id': 297, 'state_id': 12, 'district_name': 'Malappuram', 'district_code': 'KL-009', 'created_at': now},
        {'district_id': 298, 'state_id': 12, 'district_name': 'Palakkad', 'district_code': 'KL-010', 'created_at': now},
        {'district_id': 299, 'state_id': 12, 'district_name': 'Pathanamthitta', 'district_code': 'KL-011', 'created_at': now},
        {'district_id': 300, 'state_id': 12, 'district_name': 'Thiruvananthapuram', 'district_code': 'KL-012', 'created_at': now},
        {'district_id': 301, 'state_id': 12, 'district_name': 'Thrissur', 'district_code': 'KL-013', 'created_at': now},
        {'district_id': 302, 'state_id': 12, 'district_name': 'Wayanad', 'district_code': 'KL-014', 'created_at': now},
        {'district_id': 303, 'state_id': 13, 'district_name': 'Agar-Malwa', 'district_code': 'MP-001', 'created_at': now},
        {'district_id': 304, 'state_id': 13, 'district_name': 'Alirajpur', 'district_code': 'MP-002', 'created_at': now},
        {'district_id': 305, 'state_id': 13, 'district_name': 'Anuppur', 'district_code': 'MP-003', 'created_at': now},
        {'district_id': 306, 'state_id': 13, 'district_name': 'Ashoknagar', 'district_code': 'MP-004', 'created_at': now},
        {'district_id': 307, 'state_id': 13, 'district_name': 'Balaghat', 'district_code': 'MP-005', 'created_at': now},
        {'district_id': 308, 'state_id': 13, 'district_name': 'Barwani', 'district_code': 'MP-006', 'created_at': now},
        {'district_id': 309, 'state_id': 13, 'district_name': 'Betul', 'district_code': 'MP-007', 'created_at': now},
        {'district_id': 310, 'state_id': 13, 'district_name': 'Bhind', 'district_code': 'MP-008', 'created_at': now},
        {'district_id': 311, 'state_id': 13, 'district_name': 'Bhopal', 'district_code': 'MP-009', 'created_at': now},
        {'district_id': 312, 'state_id': 13, 'district_name': 'Burhanpur', 'district_code': 'MP-010', 'created_at': now},
        {'district_id': 313, 'state_id': 13, 'district_name': 'Chhatarpur', 'district_code': 'MP-011', 'created_at': now},
        {'district_id': 314, 'state_id': 13, 'district_name': 'Chhindwara', 'district_code': 'MP-012', 'created_at': now},
        {'district_id': 315, 'state_id': 13, 'district_name': 'Damoh', 'district_code': 'MP-013', 'created_at': now},
        {'district_id': 316, 'state_id': 13, 'district_name': 'Datia', 'district_code': 'MP-014', 'created_at': now},
        {'district_id': 317, 'state_id': 13, 'district_name': 'Dewas', 'district_code': 'MP-015', 'created_at': now},
        {'district_id': 318, 'state_id': 13, 'district_name': 'Dhar', 'district_code': 'MP-016', 'created_at': now},
        {'district_id': 319, 'state_id': 13, 'district_name': 'Dindori', 'district_code': 'MP-017', 'created_at': now},
        {'district_id': 320, 'state_id': 13, 'district_name': 'Guna', 'district_code': 'MP-018', 'created_at': now},
        {'district_id': 321, 'state_id': 13, 'district_name': 'Gwalior', 'district_code': 'MP-019', 'created_at': now},
        {'district_id': 322, 'state_id': 13, 'district_name': 'Harda', 'district_code': 'MP-020', 'created_at': now},
        {'district_id': 323, 'state_id': 13, 'district_name': 'Indore', 'district_code': 'MP-021', 'created_at': now},
        {'district_id': 324, 'state_id': 13, 'district_name': 'Jabalpur', 'district_code': 'MP-022', 'created_at': now},
        {'district_id': 325, 'state_id': 13, 'district_name': 'Jhabua', 'district_code': 'MP-023', 'created_at': now},
        {'district_id': 326, 'state_id': 13, 'district_name': 'Katni', 'district_code': 'MP-024', 'created_at': now},
        {'district_id': 327, 'state_id': 13, 'district_name': 'Khandwa (East Nimar)', 'district_code': 'MP-025', 'created_at': now},
        {'district_id': 328, 'state_id': 13, 'district_name': 'Khargone (West Nimar)', 'district_code': 'MP-026', 'created_at': now},
        {'district_id': 329, 'state_id': 13, 'district_name': 'Mandla', 'district_code': 'MP-027', 'created_at': now},
        {'district_id': 330, 'state_id': 13, 'district_name': 'Mandsaur', 'district_code': 'MP-028', 'created_at': now},
        {'district_id': 331, 'state_id': 13, 'district_name': 'Maihar', 'district_code': 'MP-029', 'created_at': now},
        {'district_id': 332, 'state_id': 13, 'district_name': 'Mauganj', 'district_code': 'MP-030', 'created_at': now},
        {'district_id': 333, 'state_id': 13, 'district_name': 'Morena', 'district_code': 'MP-031', 'created_at': now},
        {'district_id': 334, 'state_id': 13, 'district_name': 'Narmadapuram', 'district_code': 'MP-032', 'created_at': now},
        {'district_id': 335, 'state_id': 13, 'district_name': 'Narsinghpur', 'district_code': 'MP-033', 'created_at': now},
        {'district_id': 336, 'state_id': 13, 'district_name': 'Neemuch', 'district_code': 'MP-034', 'created_at': now},
        {'district_id': 337, 'state_id': 13, 'district_name': 'Niwari', 'district_code': 'MP-035', 'created_at': now},
        {'district_id': 338, 'state_id': 13, 'district_name': 'Panna', 'district_code': 'MP-036', 'created_at': now},
        {'district_id': 339, 'state_id': 13, 'district_name': 'Raisen', 'district_code': 'MP-037', 'created_at': now},
        {'district_id': 340, 'state_id': 13, 'district_name': 'Rajgarh', 'district_code': 'MP-038', 'created_at': now},
        {'district_id': 341, 'state_id': 13, 'district_name': 'Ratlam', 'district_code': 'MP-039', 'created_at': now},
        {'district_id': 342, 'state_id': 13, 'district_name': 'Rewa', 'district_code': 'MP-040', 'created_at': now},
        {'district_id': 343, 'state_id': 13, 'district_name': 'Sagar', 'district_code': 'MP-041', 'created_at': now},
        {'district_id': 344, 'state_id': 13, 'district_name': 'Satna', 'district_code': 'MP-042', 'created_at': now},
        {'district_id': 345, 'state_id': 13, 'district_name': 'Sehore', 'district_code': 'MP-043', 'created_at': now},
        {'district_id': 346, 'state_id': 13, 'district_name': 'Seoni', 'district_code': 'MP-044', 'created_at': now},
        {'district_id': 347, 'state_id': 13, 'district_name': 'Shahdol', 'district_code': 'MP-045', 'created_at': now},
        {'district_id': 348, 'state_id': 13, 'district_name': 'Shajapur', 'district_code': 'MP-046', 'created_at': now},
        {'district_id': 349, 'state_id': 13, 'district_name': 'Sheopur', 'district_code': 'MP-047', 'created_at': now},
        {'district_id': 350, 'state_id': 13, 'district_name': 'Shivpuri', 'district_code': 'MP-048', 'created_at': now},
        {'district_id': 351, 'state_id': 13, 'district_name': 'Sidhi', 'district_code': 'MP-049', 'created_at': now},
        {'district_id': 352, 'state_id': 13, 'district_name': 'Singrauli', 'district_code': 'MP-050', 'created_at': now},
        {'district_id': 353, 'state_id': 13, 'district_name': 'Tikamgarh', 'district_code': 'MP-051', 'created_at': now},
        {'district_id': 354, 'state_id': 13, 'district_name': 'Ujjain', 'district_code': 'MP-052', 'created_at': now},
        {'district_id': 355, 'state_id': 13, 'district_name': 'Umaria', 'district_code': 'MP-053', 'created_at': now},
        {'district_id': 356, 'state_id': 13, 'district_name': 'Vidisha', 'district_code': 'MP-054', 'created_at': now},
        {'district_id': 357, 'state_id': 13, 'district_name': 'Pandhurna', 'district_code': 'MP-055', 'created_at': now},
        {'district_id': 358, 'state_id': 14, 'district_name': 'Ahilyanagar', 'district_code': 'MH-001', 'created_at': now},
        {'district_id': 359, 'state_id': 14, 'district_name': 'Akola', 'district_code': 'MH-002', 'created_at': now},
        {'district_id': 360, 'state_id': 14, 'district_name': 'Amravati', 'district_code': 'MH-003', 'created_at': now},
        {'district_id': 361, 'state_id': 14, 'district_name': 'Beed', 'district_code': 'MH-004', 'created_at': now},
        {'district_id': 362, 'state_id': 14, 'district_name': 'Bhandara', 'district_code': 'MH-005', 'created_at': now},
        {'district_id': 363, 'state_id': 14, 'district_name': 'Buldhana', 'district_code': 'MH-006', 'created_at': now},
        {'district_id': 364, 'state_id': 14, 'district_name': 'Chandrapur', 'district_code': 'MH-007', 'created_at': now},
        {'district_id': 365, 'state_id': 14, 'district_name': 'Chhatrapati Sambhajinagar', 'district_code': 'MH-008', 'created_at': now},
        {'district_id': 366, 'state_id': 14, 'district_name': 'Dharashiv', 'district_code': 'MH-009', 'created_at': now},
        {'district_id': 367, 'state_id': 14, 'district_name': 'Dhule', 'district_code': 'MH-010', 'created_at': now},
        {'district_id': 368, 'state_id': 14, 'district_name': 'Gadchiroli', 'district_code': 'MH-011', 'created_at': now},
        {'district_id': 369, 'state_id': 14, 'district_name': 'Gondia', 'district_code': 'MH-012', 'created_at': now},
        {'district_id': 370, 'state_id': 14, 'district_name': 'Hingoli', 'district_code': 'MH-013', 'created_at': now},
        {'district_id': 371, 'state_id': 14, 'district_name': 'Jalgaon', 'district_code': 'MH-014', 'created_at': now},
        {'district_id': 372, 'state_id': 14, 'district_name': 'Jalna', 'district_code': 'MH-015', 'created_at': now},
        {'district_id': 373, 'state_id': 14, 'district_name': 'Kolhapur', 'district_code': 'MH-016', 'created_at': now},
        {'district_id': 374, 'state_id': 14, 'district_name': 'Latur', 'district_code': 'MH-017', 'created_at': now},
        {'district_id': 375, 'state_id': 14, 'district_name': 'Mumbai', 'district_code': 'MH-018', 'created_at': now},
        {'district_id': 376, 'state_id': 14, 'district_name': 'Mumbai Suburban', 'district_code': 'MH-019', 'created_at': now},
        {'district_id': 377, 'state_id': 14, 'district_name': 'Nagpur', 'district_code': 'MH-020', 'created_at': now},
        {'district_id': 378, 'state_id': 14, 'district_name': 'Nanded', 'district_code': 'MH-021', 'created_at': now},
        {'district_id': 379, 'state_id': 14, 'district_name': 'Nandurbar', 'district_code': 'MH-022', 'created_at': now},
        {'district_id': 380, 'state_id': 14, 'district_name': 'Nashik', 'district_code': 'MH-023', 'created_at': now},
        {'district_id': 381, 'state_id': 14, 'district_name': 'Palghar', 'district_code': 'MH-024', 'created_at': now},
        {'district_id': 382, 'state_id': 14, 'district_name': 'Parbhani', 'district_code': 'MH-025', 'created_at': now},
        {'district_id': 383, 'state_id': 14, 'district_name': 'Pune', 'district_code': 'MH-026', 'created_at': now},
        {'district_id': 384, 'state_id': 14, 'district_name': 'Raigad', 'district_code': 'MH-027', 'created_at': now},
        {'district_id': 385, 'state_id': 14, 'district_name': 'Ratnagiri', 'district_code': 'MH-028', 'created_at': now},
        {'district_id': 386, 'state_id': 14, 'district_name': 'Sangli', 'district_code': 'MH-029', 'created_at': now},
        {'district_id': 387, 'state_id': 14, 'district_name': 'Satara', 'district_code': 'MH-030', 'created_at': now},
        {'district_id': 388, 'state_id': 14, 'district_name': 'Sindhudurg', 'district_code': 'MH-031', 'created_at': now},
        {'district_id': 389, 'state_id': 14, 'district_name': 'Solapur', 'district_code': 'MH-032', 'created_at': now},
        {'district_id': 390, 'state_id': 14, 'district_name': 'Thane', 'district_code': 'MH-033', 'created_at': now},
        {'district_id': 391, 'state_id': 14, 'district_name': 'Wardha', 'district_code': 'MH-034', 'created_at': now},
        {'district_id': 392, 'state_id': 14, 'district_name': 'Washim', 'district_code': 'MH-035', 'created_at': now},
        {'district_id': 393, 'state_id': 14, 'district_name': 'Yavatmal', 'district_code': 'MH-036', 'created_at': now},
        {'district_id': 394, 'state_id': 15, 'district_name': 'Bishnupur', 'district_code': 'MN-001', 'created_at': now},
        {'district_id': 395, 'state_id': 15, 'district_name': 'Chandel', 'district_code': 'MN-002', 'created_at': now},
        {'district_id': 396, 'state_id': 15, 'district_name': 'Churachandpur', 'district_code': 'MN-003', 'created_at': now},
        {'district_id': 397, 'state_id': 15, 'district_name': 'Imphal East', 'district_code': 'MN-004', 'created_at': now},
        {'district_id': 398, 'state_id': 15, 'district_name': 'Imphal West', 'district_code': 'MN-005', 'created_at': now},
        {'district_id': 399, 'state_id': 15, 'district_name': 'Jiribam', 'district_code': 'MN-006', 'created_at': now},
        {'district_id': 400, 'state_id': 15, 'district_name': 'Kakching', 'district_code': 'MN-007', 'created_at': now},
        {'district_id': 401, 'state_id': 15, 'district_name': 'Kamjong', 'district_code': 'MN-008', 'created_at': now},
        {'district_id': 402, 'state_id': 15, 'district_name': 'Kangpokpi', 'district_code': 'MN-009', 'created_at': now},
        {'district_id': 403, 'state_id': 15, 'district_name': 'Noney', 'district_code': 'MN-010', 'created_at': now},
        {'district_id': 404, 'state_id': 15, 'district_name': 'Pherzawl', 'district_code': 'MN-011', 'created_at': now},
        {'district_id': 405, 'state_id': 15, 'district_name': 'Senapati', 'district_code': 'MN-012', 'created_at': now},
        {'district_id': 406, 'state_id': 15, 'district_name': 'Tamenglong', 'district_code': 'MN-013', 'created_at': now},
        {'district_id': 407, 'state_id': 15, 'district_name': 'Tengnoupal', 'district_code': 'MN-014', 'created_at': now},
        {'district_id': 408, 'state_id': 15, 'district_name': 'Thoubal', 'district_code': 'MN-015', 'created_at': now},
        {'district_id': 409, 'state_id': 15, 'district_name': 'Ukhrul', 'district_code': 'MN-016', 'created_at': now},
        {'district_id': 410, 'state_id': 16, 'district_name': 'East Garo Hills', 'district_code': 'ML-001', 'created_at': now},
        {'district_id': 411, 'state_id': 16, 'district_name': 'East Jaintia Hills', 'district_code': 'ML-002', 'created_at': now},
        {'district_id': 412, 'state_id': 16, 'district_name': 'East Khasi Hills', 'district_code': 'ML-003', 'created_at': now},
        {'district_id': 413, 'state_id': 16, 'district_name': 'Eastern West Khasi Hills', 'district_code': 'ML-004', 'created_at': now},
        {'district_id': 414, 'state_id': 16, 'district_name': 'North Garo Hills', 'district_code': 'ML-005', 'created_at': now},
        {'district_id': 415, 'state_id': 16, 'district_name': 'Ri Bhoi', 'district_code': 'ML-006', 'created_at': now},
        {'district_id': 416, 'state_id': 16, 'district_name': 'South Garo Hills', 'district_code': 'ML-007', 'created_at': now},
        {'district_id': 417, 'state_id': 16, 'district_name': 'South West Garo Hills', 'district_code': 'ML-008', 'created_at': now},
        {'district_id': 418, 'state_id': 16, 'district_name': 'South West Khasi Hills', 'district_code': 'ML-009', 'created_at': now},
        {'district_id': 419, 'state_id': 16, 'district_name': 'West Garo Hills', 'district_code': 'ML-010', 'created_at': now},
        {'district_id': 420, 'state_id': 16, 'district_name': 'West Jaintia Hills', 'district_code': 'ML-011', 'created_at': now},
        {'district_id': 421, 'state_id': 16, 'district_name': 'West Khasi Hills', 'district_code': 'ML-012', 'created_at': now},
        {'district_id': 422, 'state_id': 17, 'district_name': 'Aizawl', 'district_code': 'MZ-001', 'created_at': now},
        {'district_id': 423, 'state_id': 17, 'district_name': 'Champhai', 'district_code': 'MZ-002', 'created_at': now},
        {'district_id': 424, 'state_id': 17, 'district_name': 'Hnahthial', 'district_code': 'MZ-003', 'created_at': now},
        {'district_id': 425, 'state_id': 17, 'district_name': 'Khawzawl', 'district_code': 'MZ-004', 'created_at': now},
        {'district_id': 426, 'state_id': 17, 'district_name': 'Kolasib', 'district_code': 'MZ-005', 'created_at': now},
        {'district_id': 427, 'state_id': 17, 'district_name': 'Lawngtlai', 'district_code': 'MZ-006', 'created_at': now},
        {'district_id': 428, 'state_id': 17, 'district_name': 'Lunglei', 'district_code': 'MZ-007', 'created_at': now},
        {'district_id': 429, 'state_id': 17, 'district_name': 'Mamit', 'district_code': 'MZ-008', 'created_at': now},
        {'district_id': 430, 'state_id': 17, 'district_name': 'Saitual', 'district_code': 'MZ-009', 'created_at': now},
        {'district_id': 431, 'state_id': 17, 'district_name': 'Serchhip', 'district_code': 'MZ-010', 'created_at': now},
        {'district_id': 432, 'state_id': 17, 'district_name': 'Siaha', 'district_code': 'MZ-011', 'created_at': now},
        {'district_id': 433, 'state_id': 18, 'district_name': 'Chumoukedima', 'district_code': 'NL-001', 'created_at': now},
        {'district_id': 434, 'state_id': 18, 'district_name': 'Dimapur', 'district_code': 'NL-002', 'created_at': now},
        {'district_id': 435, 'state_id': 18, 'district_name': 'Kiphire', 'district_code': 'NL-003', 'created_at': now},
        {'district_id': 436, 'state_id': 18, 'district_name': 'Kohima', 'district_code': 'NL-004', 'created_at': now},
        {'district_id': 437, 'state_id': 18, 'district_name': 'Longleng', 'district_code': 'NL-005', 'created_at': now},
        {'district_id': 438, 'state_id': 18, 'district_name': 'Meluri', 'district_code': 'NL-006', 'created_at': now},
        {'district_id': 439, 'state_id': 18, 'district_name': 'Mokokchung', 'district_code': 'NL-007', 'created_at': now},
        {'district_id': 440, 'state_id': 18, 'district_name': 'Mon', 'district_code': 'NL-008', 'created_at': now},
        {'district_id': 441, 'state_id': 18, 'district_name': 'Niuland', 'district_code': 'NL-009', 'created_at': now},
        {'district_id': 442, 'state_id': 18, 'district_name': 'Noklak', 'district_code': 'NL-010', 'created_at': now},
        {'district_id': 443, 'state_id': 18, 'district_name': 'Peren', 'district_code': 'NL-011', 'created_at': now},
        {'district_id': 444, 'state_id': 18, 'district_name': 'Phek', 'district_code': 'NL-012', 'created_at': now},
        {'district_id': 445, 'state_id': 18, 'district_name': 'Shamator', 'district_code': 'NL-013', 'created_at': now},
        {'district_id': 446, 'state_id': 18, 'district_name': 'Tseminyu', 'district_code': 'NL-014', 'created_at': now},
        {'district_id': 447, 'state_id': 18, 'district_name': 'Tuensang', 'district_code': 'NL-015', 'created_at': now},
        {'district_id': 448, 'state_id': 18, 'district_name': 'Wokha', 'district_code': 'NL-016', 'created_at': now},
        {'district_id': 449, 'state_id': 18, 'district_name': 'Zunheboto', 'district_code': 'NL-017', 'created_at': now},
        {'district_id': 450, 'state_id': 19, 'district_name': 'Anugola', 'district_code': 'OD-001', 'created_at': now},
        {'district_id': 451, 'state_id': 19, 'district_name': 'Balangir', 'district_code': 'OD-002', 'created_at': now},
        {'district_id': 452, 'state_id': 19, 'district_name': 'Baleshwar', 'district_code': 'OD-003', 'created_at': now},
        {'district_id': 453, 'state_id': 19, 'district_name': 'Baragada', 'district_code': 'OD-004', 'created_at': now},
        {'district_id': 454, 'state_id': 19, 'district_name': 'Bhadrak', 'district_code': 'OD-005', 'created_at': now},
        {'district_id': 455, 'state_id': 19, 'district_name': 'Boudh', 'district_code': 'OD-006', 'created_at': now},
        {'district_id': 456, 'state_id': 19, 'district_name': 'Debagada', 'district_code': 'OD-007', 'created_at': now},
        {'district_id': 457, 'state_id': 19, 'district_name': 'Dhenkanal', 'district_code': 'OD-008', 'created_at': now},
        {'district_id': 458, 'state_id': 19, 'district_name': 'Gajapati', 'district_code': 'OD-009', 'created_at': now},
        {'district_id': 459, 'state_id': 19, 'district_name': 'Ganjam', 'district_code': 'OD-010', 'created_at': now},
        {'district_id': 460, 'state_id': 19, 'district_name': 'Jagatsinghapur', 'district_code': 'OD-011', 'created_at': now},
        {'district_id': 461, 'state_id': 19, 'district_name': 'Jajpur', 'district_code': 'OD-012', 'created_at': now},
        {'district_id': 462, 'state_id': 19, 'district_name': 'Jharsuguda', 'district_code': 'OD-013', 'created_at': now},
        {'district_id': 463, 'state_id': 19, 'district_name': 'Kalahandi', 'district_code': 'OD-014', 'created_at': now},
        {'district_id': 464, 'state_id': 19, 'district_name': 'Kandhamala', 'district_code': 'OD-015', 'created_at': now},
        {'district_id': 465, 'state_id': 19, 'district_name': 'Kataka', 'district_code': 'OD-016', 'created_at': now},
        {'district_id': 466, 'state_id': 19, 'district_name': 'Kendrapada', 'district_code': 'OD-017', 'created_at': now},
        {'district_id': 467, 'state_id': 19, 'district_name': 'Kendujhar', 'district_code': 'OD-018', 'created_at': now},
        {'district_id': 468, 'state_id': 19, 'district_name': 'Khordha', 'district_code': 'OD-019', 'created_at': now},
        {'district_id': 469, 'state_id': 19, 'district_name': 'Koraput', 'district_code': 'OD-020', 'created_at': now},
        {'district_id': 470, 'state_id': 19, 'district_name': 'Malkangiri', 'district_code': 'OD-021', 'created_at': now},
        {'district_id': 471, 'state_id': 19, 'district_name': 'Mayurbhanj', 'district_code': 'OD-022', 'created_at': now},
        {'district_id': 472, 'state_id': 19, 'district_name': 'Nabarangpur', 'district_code': 'OD-023', 'created_at': now},
        {'district_id': 473, 'state_id': 19, 'district_name': 'Nayagada', 'district_code': 'OD-024', 'created_at': now},
        {'district_id': 474, 'state_id': 19, 'district_name': 'Nuapada', 'district_code': 'OD-025', 'created_at': now},
        {'district_id': 475, 'state_id': 19, 'district_name': 'Puri', 'district_code': 'OD-026', 'created_at': now},
        {'district_id': 476, 'state_id': 19, 'district_name': 'Rayagada', 'district_code': 'OD-027', 'created_at': now},
        {'district_id': 477, 'state_id': 19, 'district_name': 'Sambalpur', 'district_code': 'OD-028', 'created_at': now},
        {'district_id': 478, 'state_id': 19, 'district_name': 'Subarnapur', 'district_code': 'OD-029', 'created_at': now},
        {'district_id': 479, 'state_id': 19, 'district_name': 'Sundargarh', 'district_code': 'OD-030', 'created_at': now},
        {'district_id': 480, 'state_id': 20, 'district_name': 'Amritsar', 'district_code': 'PB-001', 'created_at': now},
        {'district_id': 481, 'state_id': 20, 'district_name': 'Barnala', 'district_code': 'PB-002', 'created_at': now},
        {'district_id': 482, 'state_id': 20, 'district_name': 'Bathinda', 'district_code': 'PB-003', 'created_at': now},
        {'district_id': 483, 'state_id': 20, 'district_name': 'Faridkot', 'district_code': 'PB-004', 'created_at': now},
        {'district_id': 484, 'state_id': 20, 'district_name': 'Fatehgarh Sahib', 'district_code': 'PB-005', 'created_at': now},
        {'district_id': 485, 'state_id': 20, 'district_name': 'Fazilka', 'district_code': 'PB-006', 'created_at': now},
        {'district_id': 486, 'state_id': 20, 'district_name': 'Ferozepur', 'district_code': 'PB-007', 'created_at': now},
        {'district_id': 487, 'state_id': 20, 'district_name': 'Gurdaspur', 'district_code': 'PB-008', 'created_at': now},
        {'district_id': 488, 'state_id': 20, 'district_name': 'Hoshiarpur', 'district_code': 'PB-009', 'created_at': now},
        {'district_id': 489, 'state_id': 20, 'district_name': 'Jalandhar', 'district_code': 'PB-010', 'created_at': now},
        {'district_id': 490, 'state_id': 20, 'district_name': 'Kapurthala', 'district_code': 'PB-011', 'created_at': now},
        {'district_id': 491, 'state_id': 20, 'district_name': 'Ludhiana', 'district_code': 'PB-012', 'created_at': now},
        {'district_id': 492, 'state_id': 20, 'district_name': 'Malerkotla', 'district_code': 'PB-013', 'created_at': now},
        {'district_id': 493, 'state_id': 20, 'district_name': 'Mansa', 'district_code': 'PB-014', 'created_at': now},
        {'district_id': 494, 'state_id': 20, 'district_name': 'Moga', 'district_code': 'PB-015', 'created_at': now},
        {'district_id': 495, 'state_id': 20, 'district_name': 'Pathankot', 'district_code': 'PB-016', 'created_at': now},
        {'district_id': 496, 'state_id': 20, 'district_name': 'Patiala', 'district_code': 'PB-017', 'created_at': now},
        {'district_id': 497, 'state_id': 20, 'district_name': 'Rupnagar', 'district_code': 'PB-018', 'created_at': now},
        {'district_id': 498, 'state_id': 20, 'district_name': 'S.A.S Nagar', 'district_code': 'PB-019', 'created_at': now},
        {'district_id': 499, 'state_id': 20, 'district_name': 'Sangrur', 'district_code': 'PB-020', 'created_at': now},
        {'district_id': 500, 'state_id': 20, 'district_name': 'Shahid Bhagat Singh Nagar', 'district_code': 'PB-021', 'created_at': now},
        {'district_id': 501, 'state_id': 20, 'district_name': 'Sri Muktsar Sahib', 'district_code': 'PB-022', 'created_at': now},
        {'district_id': 502, 'state_id': 20, 'district_name': 'Tarn Taran', 'district_code': 'PB-023', 'created_at': now},
        {'district_id': 503, 'state_id': 21, 'district_name': 'Ajmer', 'district_code': 'RJ-001', 'created_at': now},
        {'district_id': 504, 'state_id': 21, 'district_name': 'Alwar', 'district_code': 'RJ-002', 'created_at': now},
        {'district_id': 505, 'state_id': 21, 'district_name': 'Balotra', 'district_code': 'RJ-003', 'created_at': now},
        {'district_id': 506, 'state_id': 21, 'district_name': 'Banswara', 'district_code': 'RJ-004', 'created_at': now},
        {'district_id': 507, 'state_id': 21, 'district_name': 'Baran', 'district_code': 'RJ-005', 'created_at': now},
        {'district_id': 508, 'state_id': 21, 'district_name': 'Barmer', 'district_code': 'RJ-006', 'created_at': now},
        {'district_id': 509, 'state_id': 21, 'district_name': 'Beawar', 'district_code': 'RJ-007', 'created_at': now},
        {'district_id': 510, 'state_id': 21, 'district_name': 'Bharatpur', 'district_code': 'RJ-008', 'created_at': now},
        {'district_id': 511, 'state_id': 21, 'district_name': 'Bhilwara', 'district_code': 'RJ-009', 'created_at': now},
        {'district_id': 512, 'state_id': 21, 'district_name': 'Bikaner', 'district_code': 'RJ-010', 'created_at': now},
        {'district_id': 513, 'state_id': 21, 'district_name': 'Bundi', 'district_code': 'RJ-011', 'created_at': now},
        {'district_id': 514, 'state_id': 21, 'district_name': 'Chittorgarh', 'district_code': 'RJ-012', 'created_at': now},
        {'district_id': 515, 'state_id': 21, 'district_name': 'Churu', 'district_code': 'RJ-013', 'created_at': now},
        {'district_id': 516, 'state_id': 21, 'district_name': 'Dausa', 'district_code': 'RJ-014', 'created_at': now},
        {'district_id': 517, 'state_id': 21, 'district_name': 'Deeg', 'district_code': 'RJ-015', 'created_at': now},
        {'district_id': 518, 'state_id': 21, 'district_name': 'Dholpur', 'district_code': 'RJ-016', 'created_at': now},
        {'district_id': 519, 'state_id': 21, 'district_name': 'Didwana-Kuchaman', 'district_code': 'RJ-017', 'created_at': now},
        {'district_id': 520, 'state_id': 21, 'district_name': 'Dungarpur', 'district_code': 'RJ-018', 'created_at': now},
        {'district_id': 521, 'state_id': 21, 'district_name': 'Ganganagar', 'district_code': 'RJ-019', 'created_at': now},
        {'district_id': 522, 'state_id': 21, 'district_name': 'Hanumangarh', 'district_code': 'RJ-020', 'created_at': now},
        {'district_id': 523, 'state_id': 21, 'district_name': 'Jaipur', 'district_code': 'RJ-021', 'created_at': now},
        {'district_id': 524, 'state_id': 21, 'district_name': 'Jaisalmer', 'district_code': 'RJ-022', 'created_at': now},
        {'district_id': 525, 'state_id': 21, 'district_name': 'Jalore', 'district_code': 'RJ-023', 'created_at': now},
        {'district_id': 526, 'state_id': 21, 'district_name': 'Jhalawar', 'district_code': 'RJ-024', 'created_at': now},
        {'district_id': 527, 'state_id': 21, 'district_name': 'Jhunjhunu', 'district_code': 'RJ-025', 'created_at': now},
        {'district_id': 528, 'state_id': 21, 'district_name': 'Jodhpur', 'district_code': 'RJ-026', 'created_at': now},
        {'district_id': 529, 'state_id': 21, 'district_name': 'Karauli', 'district_code': 'RJ-027', 'created_at': now},
        {'district_id': 530, 'state_id': 21, 'district_name': 'Khairthal-Tijara', 'district_code': 'RJ-028', 'created_at': now},
        {'district_id': 531, 'state_id': 21, 'district_name': 'Kota', 'district_code': 'RJ-029', 'created_at': now},
        {'district_id': 532, 'state_id': 21, 'district_name': 'Nagaur', 'district_code': 'RJ-030', 'created_at': now},
        {'district_id': 533, 'state_id': 21, 'district_name': 'Pali', 'district_code': 'RJ-031', 'created_at': now},
        {'district_id': 534, 'state_id': 21, 'district_name': 'Phalodi', 'district_code': 'RJ-032', 'created_at': now},
        {'district_id': 535, 'state_id': 21, 'district_name': 'Pratapgarh', 'district_code': 'RJ-033', 'created_at': now},
        {'district_id': 536, 'state_id': 21, 'district_name': 'Rajsamand', 'district_code': 'RJ-034', 'created_at': now},
        {'district_id': 537, 'state_id': 21, 'district_name': 'Salumbar', 'district_code': 'RJ-035', 'created_at': now},
        {'district_id': 538, 'state_id': 21, 'district_name': 'Sawai Madhopur', 'district_code': 'RJ-036', 'created_at': now},
        {'district_id': 539, 'state_id': 21, 'district_name': 'Sikar', 'district_code': 'RJ-037', 'created_at': now},
        {'district_id': 540, 'state_id': 21, 'district_name': 'Sirohi', 'district_code': 'RJ-038', 'created_at': now},
        {'district_id': 541, 'state_id': 21, 'district_name': 'Tonk', 'district_code': 'RJ-039', 'created_at': now},
        {'district_id': 542, 'state_id': 21, 'district_name': 'Udaipur', 'district_code': 'RJ-040', 'created_at': now},
        {'district_id': 543, 'state_id': 21, 'district_name': 'Sri Ganganagar', 'district_code': 'RJ-041', 'created_at': now},
        {'district_id': 544, 'state_id': 22, 'district_name': 'Gangtok', 'district_code': 'SK-001', 'created_at': now},
        {'district_id': 545, 'state_id': 22, 'district_name': 'Gyalshing', 'district_code': 'SK-002', 'created_at': now},
        {'district_id': 546, 'state_id': 22, 'district_name': 'Mangan', 'district_code': 'SK-003', 'created_at': now},
        {'district_id': 547, 'state_id': 22, 'district_name': 'Namchi', 'district_code': 'SK-004', 'created_at': now},
        {'district_id': 548, 'state_id': 22, 'district_name': 'Pakyong', 'district_code': 'SK-005', 'created_at': now},
        {'district_id': 549, 'state_id': 22, 'district_name': 'Soreng', 'district_code': 'SK-006', 'created_at': now},
        {'district_id': 550, 'state_id': 23, 'district_name': 'Ariyalur', 'district_code': 'TN-001', 'created_at': now},
        {'district_id': 551, 'state_id': 23, 'district_name': 'Chengalpattu', 'district_code': 'TN-002', 'created_at': now},
        {'district_id': 552, 'state_id': 23, 'district_name': 'Chennai', 'district_code': 'TN-003', 'created_at': now},
        {'district_id': 553, 'state_id': 23, 'district_name': 'Coimbatore', 'district_code': 'TN-004', 'created_at': now},
        {'district_id': 554, 'state_id': 23, 'district_name': 'Cuddalore', 'district_code': 'TN-005', 'created_at': now},
        {'district_id': 555, 'state_id': 23, 'district_name': 'Dharmapuri', 'district_code': 'TN-006', 'created_at': now},
        {'district_id': 556, 'state_id': 23, 'district_name': 'Dindigul', 'district_code': 'TN-007', 'created_at': now},
        {'district_id': 557, 'state_id': 23, 'district_name': 'Erode', 'district_code': 'TN-008', 'created_at': now},
        {'district_id': 558, 'state_id': 23, 'district_name': 'Kallakurichi', 'district_code': 'TN-009', 'created_at': now},
        {'district_id': 559, 'state_id': 23, 'district_name': 'Kancheepuram', 'district_code': 'TN-010', 'created_at': now},
        {'district_id': 560, 'state_id': 23, 'district_name': 'Kanniyakumari', 'district_code': 'TN-011', 'created_at': now},
        {'district_id': 561, 'state_id': 23, 'district_name': 'Karur', 'district_code': 'TN-012', 'created_at': now},
        {'district_id': 562, 'state_id': 23, 'district_name': 'Krishnagiri', 'district_code': 'TN-013', 'created_at': now},
        {'district_id': 563, 'state_id': 23, 'district_name': 'Madurai', 'district_code': 'TN-014', 'created_at': now},
        {'district_id': 564, 'state_id': 23, 'district_name': 'Mayiladuthurai', 'district_code': 'TN-015', 'created_at': now},
        {'district_id': 565, 'state_id': 23, 'district_name': 'Nagapattinam', 'district_code': 'TN-016', 'created_at': now},
        {'district_id': 566, 'state_id': 23, 'district_name': 'Namakkal', 'district_code': 'TN-017', 'created_at': now},
        {'district_id': 567, 'state_id': 23, 'district_name': 'Perambalur', 'district_code': 'TN-018', 'created_at': now},
        {'district_id': 568, 'state_id': 23, 'district_name': 'Pudukkottai', 'district_code': 'TN-019', 'created_at': now},
        {'district_id': 569, 'state_id': 23, 'district_name': 'Ramanathapuram', 'district_code': 'TN-020', 'created_at': now},
        {'district_id': 570, 'state_id': 23, 'district_name': 'Ranipet', 'district_code': 'TN-021', 'created_at': now},
        {'district_id': 571, 'state_id': 23, 'district_name': 'Salem', 'district_code': 'TN-022', 'created_at': now},
        {'district_id': 572, 'state_id': 23, 'district_name': 'Sivaganga', 'district_code': 'TN-023', 'created_at': now},
        {'district_id': 573, 'state_id': 23, 'district_name': 'Tenkasi', 'district_code': 'TN-024', 'created_at': now},
        {'district_id': 574, 'state_id': 23, 'district_name': 'Thanjavur', 'district_code': 'TN-025', 'created_at': now},
        {'district_id': 575, 'state_id': 23, 'district_name': 'The Nilgiris', 'district_code': 'TN-026', 'created_at': now},
        {'district_id': 576, 'state_id': 23, 'district_name': 'Theni', 'district_code': 'TN-027', 'created_at': now},
        {'district_id': 577, 'state_id': 23, 'district_name': 'Thoothukudi', 'district_code': 'TN-028', 'created_at': now},
        {'district_id': 578, 'state_id': 23, 'district_name': 'Tiruchirappalli', 'district_code': 'TN-029', 'created_at': now},
        {'district_id': 579, 'state_id': 23, 'district_name': 'Tirunelveli', 'district_code': 'TN-030', 'created_at': now},
        {'district_id': 580, 'state_id': 23, 'district_name': 'Tirupathur', 'district_code': 'TN-031', 'created_at': now},
        {'district_id': 581, 'state_id': 23, 'district_name': 'Tiruppur', 'district_code': 'TN-032', 'created_at': now},
        {'district_id': 582, 'state_id': 23, 'district_name': 'Tiruvallur', 'district_code': 'TN-033', 'created_at': now},
        {'district_id': 583, 'state_id': 23, 'district_name': 'Tiruvannamalai', 'district_code': 'TN-034', 'created_at': now},
        {'district_id': 584, 'state_id': 23, 'district_name': 'Tiruvarur', 'district_code': 'TN-035', 'created_at': now},
        {'district_id': 585, 'state_id': 23, 'district_name': 'Vellore', 'district_code': 'TN-036', 'created_at': now},
        {'district_id': 586, 'state_id': 23, 'district_name': 'Viluppuram', 'district_code': 'TN-037', 'created_at': now},
        {'district_id': 587, 'state_id': 23, 'district_name': 'Virudhunagar', 'district_code': 'TN-038', 'created_at': now},
        {'district_id': 588, 'state_id': 24, 'district_name': 'Adilabad', 'district_code': 'TS-001', 'created_at': now},
        {'district_id': 589, 'state_id': 24, 'district_name': 'Bhadradri Kothagudem', 'district_code': 'TS-002', 'created_at': now},
        {'district_id': 590, 'state_id': 24, 'district_name': 'Hanumakonda', 'district_code': 'TS-003', 'created_at': now},
        {'district_id': 591, 'state_id': 24, 'district_name': 'Hyderabad', 'district_code': 'TS-004', 'created_at': now},
        {'district_id': 592, 'state_id': 24, 'district_name': 'Jagitial', 'district_code': 'TS-005', 'created_at': now},
        {'district_id': 593, 'state_id': 24, 'district_name': 'Jangoan', 'district_code': 'TS-006', 'created_at': now},
        {'district_id': 594, 'state_id': 24, 'district_name': 'Jayashankar Bhupalapally', 'district_code': 'TS-007', 'created_at': now},
        {'district_id': 595, 'state_id': 24, 'district_name': 'Jogulamba Gadwal', 'district_code': 'TS-008', 'created_at': now},
        {'district_id': 596, 'state_id': 24, 'district_name': 'Kamareddy', 'district_code': 'TS-009', 'created_at': now},
        {'district_id': 597, 'state_id': 24, 'district_name': 'Karimnagar', 'district_code': 'TS-010', 'created_at': now},
        {'district_id': 598, 'state_id': 24, 'district_name': 'Khammam', 'district_code': 'TS-011', 'created_at': now},
        {'district_id': 599, 'state_id': 24, 'district_name': 'Kumuram Bheem Asifabad', 'district_code': 'TS-012', 'created_at': now},
        {'district_id': 600, 'state_id': 24, 'district_name': 'Mahabubabad', 'district_code': 'TS-013', 'created_at': now},
        {'district_id': 601, 'state_id': 24, 'district_name': 'Mahabubnagar', 'district_code': 'TS-014', 'created_at': now},
        {'district_id': 602, 'state_id': 24, 'district_name': 'Mancherial', 'district_code': 'TS-015', 'created_at': now},
        {'district_id': 603, 'state_id': 24, 'district_name': 'Medak', 'district_code': 'TS-016', 'created_at': now},
        {'district_id': 604, 'state_id': 24, 'district_name': 'Medchal Malkajgiri', 'district_code': 'TS-017', 'created_at': now},
        {'district_id': 605, 'state_id': 24, 'district_name': 'Mulugu', 'district_code': 'TS-018', 'created_at': now},
        {'district_id': 606, 'state_id': 24, 'district_name': 'Nagarkurnool', 'district_code': 'TS-019', 'created_at': now},
        {'district_id': 607, 'state_id': 24, 'district_name': 'Nalgonda', 'district_code': 'TS-020', 'created_at': now},
        {'district_id': 608, 'state_id': 24, 'district_name': 'Narayanpet', 'district_code': 'TS-021', 'created_at': now},
        {'district_id': 609, 'state_id': 24, 'district_name': 'Nirmal', 'district_code': 'TS-022', 'created_at': now},
        {'district_id': 610, 'state_id': 24, 'district_name': 'Nizamabad', 'district_code': 'TS-023', 'created_at': now},
        {'district_id': 611, 'state_id': 24, 'district_name': 'Peddapalli', 'district_code': 'TS-024', 'created_at': now},
        {'district_id': 612, 'state_id': 24, 'district_name': 'Rajanna Sircilla', 'district_code': 'TS-025', 'created_at': now},
        {'district_id': 613, 'state_id': 24, 'district_name': 'Rangareddy', 'district_code': 'TS-026', 'created_at': now},
        {'district_id': 614, 'state_id': 24, 'district_name': 'Sangareddy', 'district_code': 'TS-027', 'created_at': now},
        {'district_id': 615, 'state_id': 24, 'district_name': 'Siddipet', 'district_code': 'TS-028', 'created_at': now},
        {'district_id': 616, 'state_id': 24, 'district_name': 'Suryapet', 'district_code': 'TS-029', 'created_at': now},
        {'district_id': 617, 'state_id': 24, 'district_name': 'Vikarabad', 'district_code': 'TS-030', 'created_at': now},
        {'district_id': 618, 'state_id': 24, 'district_name': 'Wanaparthy', 'district_code': 'TS-031', 'created_at': now},
        {'district_id': 619, 'state_id': 24, 'district_name': 'Warangal', 'district_code': 'TS-032', 'created_at': now},
        {'district_id': 620, 'state_id': 24, 'district_name': 'Yadadri Bhuvanagiri', 'district_code': 'TS-033', 'created_at': now},
        {'district_id': 621, 'state_id': 25, 'district_name': 'Dhalai', 'district_code': 'TR-001', 'created_at': now},
        {'district_id': 622, 'state_id': 25, 'district_name': 'Gomati', 'district_code': 'TR-002', 'created_at': now},
        {'district_id': 623, 'state_id': 25, 'district_name': 'Khowai', 'district_code': 'TR-003', 'created_at': now},
        {'district_id': 624, 'state_id': 25, 'district_name': 'North Tripura', 'district_code': 'TR-004', 'created_at': now},
        {'district_id': 625, 'state_id': 25, 'district_name': 'Sepahijala', 'district_code': 'TR-005', 'created_at': now},
        {'district_id': 626, 'state_id': 25, 'district_name': 'South Tripura', 'district_code': 'TR-006', 'created_at': now},
        {'district_id': 627, 'state_id': 25, 'district_name': 'Unakoti', 'district_code': 'TR-007', 'created_at': now},
        {'district_id': 628, 'state_id': 25, 'district_name': 'West Tripura', 'district_code': 'TR-008', 'created_at': now},
        {'district_id': 629, 'state_id': 26, 'district_name': 'Agra', 'district_code': 'UP-001', 'created_at': now},
        {'district_id': 630, 'state_id': 26, 'district_name': 'Aligarh', 'district_code': 'UP-002', 'created_at': now},
        {'district_id': 631, 'state_id': 26, 'district_name': 'Ambedkar Nagar', 'district_code': 'UP-003', 'created_at': now},
        {'district_id': 632, 'state_id': 26, 'district_name': 'Amethi', 'district_code': 'UP-004', 'created_at': now},
        {'district_id': 633, 'state_id': 26, 'district_name': 'Amroha', 'district_code': 'UP-005', 'created_at': now},
        {'district_id': 634, 'state_id': 26, 'district_name': 'Auraiya', 'district_code': 'UP-006', 'created_at': now},
        {'district_id': 635, 'state_id': 26, 'district_name': 'Ayodhya', 'district_code': 'UP-007', 'created_at': now},
        {'district_id': 636, 'state_id': 26, 'district_name': 'Azamgarh', 'district_code': 'UP-008', 'created_at': now},
        {'district_id': 637, 'state_id': 26, 'district_name': 'Baghpat', 'district_code': 'UP-009', 'created_at': now},
        {'district_id': 638, 'state_id': 26, 'district_name': 'Bahraich', 'district_code': 'UP-010', 'created_at': now},
        {'district_id': 639, 'state_id': 26, 'district_name': 'Ballia', 'district_code': 'UP-011', 'created_at': now},
        {'district_id': 640, 'state_id': 26, 'district_name': 'Balrampur', 'district_code': 'UP-012', 'created_at': now},
        {'district_id': 641, 'state_id': 26, 'district_name': 'Banda', 'district_code': 'UP-013', 'created_at': now},
        {'district_id': 642, 'state_id': 26, 'district_name': 'Bara Banki', 'district_code': 'UP-014', 'created_at': now},
        {'district_id': 643, 'state_id': 26, 'district_name': 'Bareilly', 'district_code': 'UP-015', 'created_at': now},
        {'district_id': 644, 'state_id': 26, 'district_name': 'Basti', 'district_code': 'UP-016', 'created_at': now},
        {'district_id': 645, 'state_id': 26, 'district_name': 'Bhadohi', 'district_code': 'UP-017', 'created_at': now},
        {'district_id': 646, 'state_id': 26, 'district_name': 'Bijnor', 'district_code': 'UP-018', 'created_at': now},
        {'district_id': 647, 'state_id': 26, 'district_name': 'Budaun', 'district_code': 'UP-019', 'created_at': now},
        {'district_id': 648, 'state_id': 26, 'district_name': 'Bulandshahr', 'district_code': 'UP-020', 'created_at': now},
        {'district_id': 649, 'state_id': 26, 'district_name': 'Chandauli', 'district_code': 'UP-021', 'created_at': now},
        {'district_id': 650, 'state_id': 26, 'district_name': 'Chitrakoot', 'district_code': 'UP-022', 'created_at': now},
        {'district_id': 651, 'state_id': 26, 'district_name': 'Deoria', 'district_code': 'UP-023', 'created_at': now},
        {'district_id': 652, 'state_id': 26, 'district_name': 'Etah', 'district_code': 'UP-024', 'created_at': now},
        {'district_id': 653, 'state_id': 26, 'district_name': 'Etawah', 'district_code': 'UP-025', 'created_at': now},
        {'district_id': 654, 'state_id': 26, 'district_name': 'Farrukhabad', 'district_code': 'UP-026', 'created_at': now},
        {'district_id': 655, 'state_id': 26, 'district_name': 'Fatehpur', 'district_code': 'UP-027', 'created_at': now},
        {'district_id': 656, 'state_id': 26, 'district_name': 'Firozabad', 'district_code': 'UP-028', 'created_at': now},
        {'district_id': 657, 'state_id': 26, 'district_name': 'Gautam Buddha Nagar', 'district_code': 'UP-029', 'created_at': now},
        {'district_id': 658, 'state_id': 26, 'district_name': 'Ghaziabad', 'district_code': 'UP-030', 'created_at': now},
        {'district_id': 659, 'state_id': 26, 'district_name': 'Ghazipur', 'district_code': 'UP-031', 'created_at': now},
        {'district_id': 660, 'state_id': 26, 'district_name': 'Gonda', 'district_code': 'UP-032', 'created_at': now},
        {'district_id': 661, 'state_id': 26, 'district_name': 'Gorakhpur', 'district_code': 'UP-033', 'created_at': now},
        {'district_id': 662, 'state_id': 26, 'district_name': 'Hamirpur', 'district_code': 'UP-034', 'created_at': now},
        {'district_id': 663, 'state_id': 26, 'district_name': 'Hapur', 'district_code': 'UP-035', 'created_at': now},
        {'district_id': 664, 'state_id': 26, 'district_name': 'Hardoi', 'district_code': 'UP-036', 'created_at': now},
        {'district_id': 665, 'state_id': 26, 'district_name': 'Hathras', 'district_code': 'UP-037', 'created_at': now},
        {'district_id': 666, 'state_id': 26, 'district_name': 'Jalaun', 'district_code': 'UP-038', 'created_at': now},
        {'district_id': 667, 'state_id': 26, 'district_name': 'Jaunpur', 'district_code': 'UP-039', 'created_at': now},
        {'district_id': 668, 'state_id': 26, 'district_name': 'Jhansi', 'district_code': 'UP-040', 'created_at': now},
        {'district_id': 669, 'state_id': 26, 'district_name': 'Kannauj', 'district_code': 'UP-041', 'created_at': now},
        {'district_id': 670, 'state_id': 26, 'district_name': 'Kanpur Dehat', 'district_code': 'UP-042', 'created_at': now},
        {'district_id': 671, 'state_id': 26, 'district_name': 'Kanpur Nagar', 'district_code': 'UP-043', 'created_at': now},
        {'district_id': 672, 'state_id': 26, 'district_name': 'Kasganj', 'district_code': 'UP-044', 'created_at': now},
        {'district_id': 673, 'state_id': 26, 'district_name': 'Kaushambi', 'district_code': 'UP-045', 'created_at': now},
        {'district_id': 674, 'state_id': 26, 'district_name': 'Kheri', 'district_code': 'UP-046', 'created_at': now},
        {'district_id': 675, 'state_id': 26, 'district_name': 'Kushinagar', 'district_code': 'UP-047', 'created_at': now},
        {'district_id': 676, 'state_id': 26, 'district_name': 'Lalitpur', 'district_code': 'UP-048', 'created_at': now},
        {'district_id': 677, 'state_id': 26, 'district_name': 'Lucknow', 'district_code': 'UP-049', 'created_at': now},
        {'district_id': 678, 'state_id': 26, 'district_name': 'Maharajganj', 'district_code': 'UP-050', 'created_at': now},
        {'district_id': 679, 'state_id': 26, 'district_name': 'Mahoba', 'district_code': 'UP-051', 'created_at': now},
        {'district_id': 680, 'state_id': 26, 'district_name': 'Mainpuri', 'district_code': 'UP-052', 'created_at': now},
        {'district_id': 681, 'state_id': 26, 'district_name': 'Mathura', 'district_code': 'UP-053', 'created_at': now},
        {'district_id': 682, 'state_id': 26, 'district_name': 'Mau', 'district_code': 'UP-054', 'created_at': now},
        {'district_id': 683, 'state_id': 26, 'district_name': 'Meerut', 'district_code': 'UP-055', 'created_at': now},
        {'district_id': 684, 'state_id': 26, 'district_name': 'Mirzapur', 'district_code': 'UP-056', 'created_at': now},
        {'district_id': 685, 'state_id': 26, 'district_name': 'Moradabad', 'district_code': 'UP-057', 'created_at': now},
        {'district_id': 686, 'state_id': 26, 'district_name': 'Muzaffarnagar', 'district_code': 'UP-058', 'created_at': now},
        {'district_id': 687, 'state_id': 26, 'district_name': 'Pilibhit', 'district_code': 'UP-059', 'created_at': now},
        {'district_id': 688, 'state_id': 26, 'district_name': 'Pratapgarh', 'district_code': 'UP-060', 'created_at': now},
        {'district_id': 689, 'state_id': 26, 'district_name': 'Prayagraj', 'district_code': 'UP-061', 'created_at': now},
        {'district_id': 690, 'state_id': 26, 'district_name': 'Raebareli', 'district_code': 'UP-062', 'created_at': now},
        {'district_id': 691, 'state_id': 26, 'district_name': 'Rampur', 'district_code': 'UP-063', 'created_at': now},
        {'district_id': 692, 'state_id': 26, 'district_name': 'Saharanpur', 'district_code': 'UP-064', 'created_at': now},
        {'district_id': 693, 'state_id': 26, 'district_name': 'Sambhal', 'district_code': 'UP-065', 'created_at': now},
        {'district_id': 694, 'state_id': 26, 'district_name': 'Sant Kabir Nagar', 'district_code': 'UP-066', 'created_at': now},
        {'district_id': 695, 'state_id': 26, 'district_name': 'Shahjahanpur', 'district_code': 'UP-067', 'created_at': now},
        {'district_id': 696, 'state_id': 26, 'district_name': 'Shamli', 'district_code': 'UP-068', 'created_at': now},
        {'district_id': 697, 'state_id': 26, 'district_name': 'Shrawasti', 'district_code': 'UP-069', 'created_at': now},
        {'district_id': 698, 'state_id': 26, 'district_name': 'Siddharthnagar', 'district_code': 'UP-070', 'created_at': now},
        {'district_id': 699, 'state_id': 26, 'district_name': 'Sitapur', 'district_code': 'UP-071', 'created_at': now},
        {'district_id': 700, 'state_id': 26, 'district_name': 'Sonbhadra', 'district_code': 'UP-072', 'created_at': now},
        {'district_id': 701, 'state_id': 26, 'district_name': 'Sultanpur', 'district_code': 'UP-073', 'created_at': now},
        {'district_id': 702, 'state_id': 26, 'district_name': 'Unnao', 'district_code': 'UP-074', 'created_at': now},
        {'district_id': 703, 'state_id': 26, 'district_name': 'Varanasi', 'district_code': 'UP-075', 'created_at': now},
        {'district_id': 704, 'state_id': 27, 'district_name': 'Almora', 'district_code': 'UK-001', 'created_at': now},
        {'district_id': 705, 'state_id': 27, 'district_name': 'Bageshwar', 'district_code': 'UK-002', 'created_at': now},
        {'district_id': 706, 'state_id': 27, 'district_name': 'Chamoli', 'district_code': 'UK-003', 'created_at': now},
        {'district_id': 707, 'state_id': 27, 'district_name': 'Champawat', 'district_code': 'UK-004', 'created_at': now},
        {'district_id': 708, 'state_id': 27, 'district_name': 'Dehradun', 'district_code': 'UK-005', 'created_at': now},
        {'district_id': 709, 'state_id': 27, 'district_name': 'Haridwar', 'district_code': 'UK-006', 'created_at': now},
        {'district_id': 710, 'state_id': 27, 'district_name': 'Nainital', 'district_code': 'UK-007', 'created_at': now},
        {'district_id': 711, 'state_id': 27, 'district_name': 'Pauri Garhwal', 'district_code': 'UK-008', 'created_at': now},
        {'district_id': 712, 'state_id': 27, 'district_name': 'Pithoragarh', 'district_code': 'UK-009', 'created_at': now},
        {'district_id': 713, 'state_id': 27, 'district_name': 'Rudraprayag', 'district_code': 'UK-010', 'created_at': now},
        {'district_id': 714, 'state_id': 27, 'district_name': 'Tehri Garhwal', 'district_code': 'UK-011', 'created_at': now},
        {'district_id': 715, 'state_id': 27, 'district_name': 'Udham Singh Nagar', 'district_code': 'UK-012', 'created_at': now},
        {'district_id': 716, 'state_id': 27, 'district_name': 'Uttarkashi', 'district_code': 'UK-013', 'created_at': now},
        {'district_id': 717, 'state_id': 28, 'district_name': 'Alipurduar', 'district_code': 'WB-001', 'created_at': now},
        {'district_id': 718, 'state_id': 28, 'district_name': 'Bankura', 'district_code': 'WB-002', 'created_at': now},
        {'district_id': 719, 'state_id': 28, 'district_name': 'Birbhum', 'district_code': 'WB-003', 'created_at': now},
        {'district_id': 720, 'state_id': 28, 'district_name': 'Cooch Behar', 'district_code': 'WB-004', 'created_at': now},
        {'district_id': 721, 'state_id': 28, 'district_name': 'Dakshin Dinajpur', 'district_code': 'WB-005', 'created_at': now},
        {'district_id': 722, 'state_id': 28, 'district_name': 'Darjeeling', 'district_code': 'WB-006', 'created_at': now},
        {'district_id': 723, 'state_id': 28, 'district_name': 'Hooghly', 'district_code': 'WB-007', 'created_at': now},
        {'district_id': 724, 'state_id': 28, 'district_name': 'Howrah', 'district_code': 'WB-008', 'created_at': now},
        {'district_id': 725, 'state_id': 28, 'district_name': 'Jalpaiguri', 'district_code': 'WB-009', 'created_at': now},
        {'district_id': 726, 'state_id': 28, 'district_name': 'Jhargram', 'district_code': 'WB-010', 'created_at': now},
        {'district_id': 727, 'state_id': 28, 'district_name': 'Kalimpong', 'district_code': 'WB-011', 'created_at': now},
        {'district_id': 728, 'state_id': 28, 'district_name': 'Kolkata', 'district_code': 'WB-012', 'created_at': now},
        {'district_id': 729, 'state_id': 28, 'district_name': 'Malda', 'district_code': 'WB-013', 'created_at': now},
        {'district_id': 730, 'state_id': 28, 'district_name': 'Murshidabad', 'district_code': 'WB-014', 'created_at': now},
        {'district_id': 731, 'state_id': 28, 'district_name': 'Nadia', 'district_code': 'WB-015', 'created_at': now},
        {'district_id': 732, 'state_id': 28, 'district_name': 'North 24 Parganas', 'district_code': 'WB-016', 'created_at': now},
        {'district_id': 733, 'state_id': 28, 'district_name': 'Paschim Bardhaman', 'district_code': 'WB-017', 'created_at': now},
        {'district_id': 734, 'state_id': 28, 'district_name': 'Paschim Medinipur', 'district_code': 'WB-018', 'created_at': now},
        {'district_id': 735, 'state_id': 28, 'district_name': 'Purba Bardhaman', 'district_code': 'WB-019', 'created_at': now},
        {'district_id': 736, 'state_id': 28, 'district_name': 'Purba Medinipur', 'district_code': 'WB-020', 'created_at': now},
        {'district_id': 737, 'state_id': 28, 'district_name': 'Purulia', 'district_code': 'WB-021', 'created_at': now},
        {'district_id': 738, 'state_id': 28, 'district_name': 'South 24 Parganas', 'district_code': 'WB-022', 'created_at': now},
        {'district_id': 739, 'state_id': 28, 'district_name': 'Uttar Dinajpur', 'district_code': 'WB-023', 'created_at': now},
        {'district_id': 740, 'state_id': 29, 'district_name': 'Nicobars', 'district_code': 'AN-001', 'created_at': now},
        {'district_id': 741, 'state_id': 29, 'district_name': 'North And Middle Andaman', 'district_code': 'AN-002', 'created_at': now},
        {'district_id': 742, 'state_id': 29, 'district_name': 'South Andamans', 'district_code': 'AN-003', 'created_at': now},
        {'district_id': 743, 'state_id': 30, 'district_name': 'Chandigarh', 'district_code': 'CH-001', 'created_at': now},
        {'district_id': 744, 'state_id': 31, 'district_name': 'Dadra And Nagar Haveli', 'district_code': 'DH-001', 'created_at': now},
        {'district_id': 745, 'state_id': 31, 'district_name': 'Daman', 'district_code': 'DH-002', 'created_at': now},
        {'district_id': 746, 'state_id': 31, 'district_name': 'Diu', 'district_code': 'DH-003', 'created_at': now},
        {'district_id': 747, 'state_id': 32, 'district_name': 'Central', 'district_code': 'DL-001', 'created_at': now},
        {'district_id': 748, 'state_id': 32, 'district_name': 'Central North', 'district_code': 'DL-002', 'created_at': now},
        {'district_id': 749, 'state_id': 32, 'district_name': 'East', 'district_code': 'DL-003', 'created_at': now},
        {'district_id': 750, 'state_id': 32, 'district_name': 'New Delhi', 'district_code': 'DL-004', 'created_at': now},
        {'district_id': 751, 'state_id': 32, 'district_name': 'North', 'district_code': 'DL-005', 'created_at': now},
        {'district_id': 752, 'state_id': 32, 'district_name': 'North East', 'district_code': 'DL-006', 'created_at': now},
        {'district_id': 753, 'state_id': 32, 'district_name': 'North West', 'district_code': 'DL-007', 'created_at': now},
        {'district_id': 754, 'state_id': 32, 'district_name': 'Old Delhi', 'district_code': 'DL-008', 'created_at': now},
        {'district_id': 755, 'state_id': 32, 'district_name': 'Outer North', 'district_code': 'DL-009', 'created_at': now},
        {'district_id': 756, 'state_id': 32, 'district_name': 'South', 'district_code': 'DL-010', 'created_at': now},
        {'district_id': 757, 'state_id': 32, 'district_name': 'South East', 'district_code': 'DL-011', 'created_at': now},
        {'district_id': 758, 'state_id': 32, 'district_name': 'South West', 'district_code': 'DL-012', 'created_at': now},
        {'district_id': 759, 'state_id': 32, 'district_name': 'West', 'district_code': 'DL-013', 'created_at': now},
        {'district_id': 760, 'state_id': 33, 'district_name': 'Anantnag', 'district_code': 'JK-001', 'created_at': now},
        {'district_id': 761, 'state_id': 33, 'district_name': 'Bandipora', 'district_code': 'JK-002', 'created_at': now},
        {'district_id': 762, 'state_id': 33, 'district_name': 'Baramulla', 'district_code': 'JK-003', 'created_at': now},
        {'district_id': 763, 'state_id': 33, 'district_name': 'Budgam', 'district_code': 'JK-004', 'created_at': now},
        {'district_id': 764, 'state_id': 33, 'district_name': 'Doda', 'district_code': 'JK-005', 'created_at': now},
        {'district_id': 765, 'state_id': 33, 'district_name': 'Ganderbal', 'district_code': 'JK-006', 'created_at': now},
        {'district_id': 766, 'state_id': 33, 'district_name': 'Jammu', 'district_code': 'JK-007', 'created_at': now},
        {'district_id': 767, 'state_id': 33, 'district_name': 'Kathua', 'district_code': 'JK-008', 'created_at': now},
        {'district_id': 768, 'state_id': 33, 'district_name': 'Kishtwar', 'district_code': 'JK-009', 'created_at': now},
        {'district_id': 769, 'state_id': 33, 'district_name': 'Kulgam', 'district_code': 'JK-010', 'created_at': now},
        {'district_id': 770, 'state_id': 33, 'district_name': 'Kupwara', 'district_code': 'JK-011', 'created_at': now},
        {'district_id': 771, 'state_id': 33, 'district_name': 'Poonch', 'district_code': 'JK-012', 'created_at': now},
        {'district_id': 772, 'state_id': 33, 'district_name': 'Pulwama', 'district_code': 'JK-013', 'created_at': now},
        {'district_id': 773, 'state_id': 33, 'district_name': 'Rajouri', 'district_code': 'JK-014', 'created_at': now},
        {'district_id': 774, 'state_id': 33, 'district_name': 'Ramban', 'district_code': 'JK-015', 'created_at': now},
        {'district_id': 775, 'state_id': 33, 'district_name': 'Reasi', 'district_code': 'JK-016', 'created_at': now},
        {'district_id': 776, 'state_id': 33, 'district_name': 'Samba', 'district_code': 'JK-017', 'created_at': now},
        {'district_id': 777, 'state_id': 33, 'district_name': 'Shopian', 'district_code': 'JK-018', 'created_at': now},
        {'district_id': 778, 'state_id': 33, 'district_name': 'Srinagar', 'district_code': 'JK-019', 'created_at': now},
        {'district_id': 779, 'state_id': 33, 'district_name': 'Udhampur', 'district_code': 'JK-020', 'created_at': now},
        {'district_id': 780, 'state_id': 34, 'district_name': 'Kargil', 'district_code': 'LA-001', 'created_at': now},
        {'district_id': 781, 'state_id': 34, 'district_name': 'Leh Ladakh', 'district_code': 'LA-002', 'created_at': now},
        {'district_id': 782, 'state_id': 35, 'district_name': 'Lakshadweep', 'district_code': 'LD-001', 'created_at': now},
        {'district_id': 783, 'state_id': 36, 'district_name': 'Karaikal', 'district_code': 'PY-001', 'created_at': now},
        {'district_id': 784, 'state_id': 36, 'district_name': 'Puducherry', 'district_code': 'PY-002', 'created_at': now},
    ]

    await states_collection.create_index(
        [("state_id", ASCENDING)],
        name="idx_state_id",
        unique=True,
    )

    await districts_collection.create_indexes([
        IndexModel(
            [("district_id", ASCENDING)],
            name="idx_district_id",
            unique=True,
        ),
        IndexModel(
            [("state_id", ASCENDING)],
            name="idx_district_state_id",
        ),
    ])

    await states_collection.bulk_write([
        UpdateOne(
            {"state_id": state["state_id"]},
            {"$set": state},
            upsert=True,
        )
        for state in states
    ])

    await districts_collection.bulk_write([
        UpdateOne(
            {"district_id": district["district_id"]},
            {"$set": district},
            upsert=True,
        )
        for district in districts
    ])


async def down():
    db = get_database()
    await db["states"].delete_many({})
    await db["districts"].delete_many({})