apiVersion: v1
kind: Service
metadata:
  name: health-institute-postgres-external-service
  namespace: arogyalink
spec:
  type: NodePort
  selector:
    app: health-institute-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30434
