syntax = "proto3";

package auth;

service AuthService {
  rpc HealthInstituteRegistration(HealthInstituteRegReq) returns (HealthInstituteRegRes);

  rpc CompensateHealthInstituteRegistration(CompensateHealthInstituteRegistrationReq) returns (CompensateHealthInstituteRegistrationRes);

  rpc HealthInstituteLogin(HealthInstituteLoginReq) returns (HealthInstituteLoginRes);

  rpc CreateDoctorAuth(DoctorRegistrationReq) returns (DoctorRegistrationRes);

  rpc CompensateDoctorRegistration(CompensateDoctorRegistrationReq) returns (CompensateDoctorRegistrationRes);

  rpc DoctorLogin(DoctorLoginReq) returns (DoctorLoginRes);

  rpc RefreshToken(RefreshTokenReq) returns (RefreshTokenRes);

  rpc Logout(LogoutReq) returns (LogoutRes);

  rpc ValidateAccessToken(ValidateAccessTokenReq) returns (ValidateAccessTokenRes);
}

message HealthInstituteRegReq {
  string email = 1;
  string password = 2;
  int32 healthInstituteType = 3;
}

message HealthInstituteRegRes {
  uint32 healthInstitutePrimaryKey = 1;
  string healthInstituteId         = 2;
}
message CompensateHealthInstituteRegistrationReq {
  uint32 healthInstitutePrimaryKey = 1;
}

message CompensateHealthInstituteRegistrationRes {
  bool success = 1;
}

message HealthInstituteLoginReq {
  string email = 1;
  string password = 2;
  string requestIp = 3;
  string userAgent = 4;
  optional string deviceName = 5;
}

message HealthInstituteLoginRes {
  string healthInstituteId = 1;
  string email = 2;
  string accessToken = 3;
  string refreshToken = 4;
}

message DoctorRegistrationReq {
  string email = 1;
  string mobile = 2;
  string password = 3;
}

message DoctorRegistrationRes {
  string doctorId = 1;
}

message CompensateDoctorRegistrationReq {
  string doctorId = 1;
}

message CompensateDoctorRegistrationRes {
  bool success = 1;
}

message DoctorLoginReq {
  optional string email = 1;
  optional string mobile = 2;
  string password = 3;
  string requestIp = 4;
  string userAgent = 5;
  optional string deviceName = 6;
}

message DoctorLoginRes {
  string doctorId = 1;
  string email = 2;
  string mobile = 3;
  string accessToken = 4;
  string refreshToken = 5;
}

message RefreshTokenReq {
  string refreshToken = 1;
}

message RefreshTokenRes {
  string accessToken = 1;
  string refreshToken = 2;
}

message LogoutReq {
  string sessionId = 1;
}

message LogoutRes {
  bool success = 1;
}

message ValidateAccessTokenReq {
  string sessionId = 1;
}

message ValidateAccessTokenRes {
  bool valid = 1;
}
