syntax = "proto3";

package auth;

service AuthService {
  rpc HealthInstituteRegistration(HealthInstituteRegReq)
  returns (HealthInstituteRegRes);

  rpc HealthInstituteLogin(HealthInstituteLoginReq)
  returns (HealthInstituteLoginRes);

  rpc CreateDoctorAuth(DoctorRegistrationReq)
  returns (DoctorRegistrationRes);

  rpc CompensateDoctorRegistration(CompensateDoctorRegistrationReq)
  returns (CompensateDoctorRegistrationRes);

  rpc DoctorLogin(DoctorLoginReq)
  returns (DoctorLoginRes);

  rpc RefreshToken(RefreshTokenReq)
  returns (RefreshTokenRes);

}

message HealthInstituteRegReq {
  int32  healthInstituteType = 1;
  string email               = 2;
  string healthInstituteName = 3;
  string password            = 4;
}

message HealthInstituteRegRes {
  string healthInstituteId = 1;
}

message HealthInstituteLoginReq {
  optional string healthInstituteId = 1;
  optional string email             = 2;
  string          password          = 3;
  string          requestIp         = 4;
  string          userAgent         = 5;
  optional string deviceName        = 6;
}

message HealthInstituteLoginRes {
  string healthInstituteId   = 1;
  string healthInstituteName = 2;
  string healthInstituteType = 3;
  string email               = 4;
  string accessToken         = 5;
  string refreshToken        = 6;
}

message DoctorRegistrationReq {
  string email    = 1;
  string mobile   = 2;
  string password = 3;
}

message DoctorRegistrationRes {
  string doctorId = 1;
}

message CompensateDoctorRegistrationReq {
  string doctorId = 1;
}

message CompensateDoctorRegistrationRes {
  bool success = 1;
}

message DoctorLoginReq {
  optional string email      = 1;
  optional string mobile     = 2;
  string          password   = 3;
  string          requestIp  = 4;
  string          userAgent  = 5;
  optional string deviceName = 6;
}

message DoctorLoginRes {
  string doctorId     = 1;
  string email        = 2;
  string mobile       = 3;
  string accessToken  = 4;
  string refreshToken = 5;
}

message RefreshTokenReq{
  string refreshToken = 1;
}

message RefreshTokenRes{
  string accessToken  = 1;
  string refreshToken = 2;
}