syntax = "proto3";

package health_institute;

service HealthInstituteService {
  rpc CreateHealthInstituteProfile(HealthInstituteProfileReq) returns (HealthInstituteProfileRes);

  rpc UpdateHealthInstituteProfile(UpdateHealthInstituteProfileReq) returns (UpdateHealthInstituteProfileRes);

  rpc GetHealthInstituteDetails(GetHealthInstituteDetailsReq) returns (GetHealthInstituteDetailsRes);

  rpc GetStates(GetStatesReq) returns (GetStatesRes);

  rpc GetDistricts(GetDistrictsReq) returns (GetDistrictsRes);

  rpc GetRegistrationCouncils(GetRegistrationCouncilReq) returns (GetRegistrationCouncilRes);

  rpc GetAppointDoctorMasterData(GetAppointDoctorMasterDataReq) returns (GetAppointDoctorMasterDataRes);

  rpc AppointDoctor(AppointDoctorReq) returns (AppointDoctorRes);
}

message HealthInstituteProfileReq {
  string healthInstituteId   = 1;
  string healthInstituteName = 2;
  int32  healthInstituteType = 3;
  string email               = 4;
}

message HealthInstituteProfileRes {
  string healthInstituteId = 1;
}

message UpdateHealthInstituteProfileReq {
  string          healthInstituteId  = 1;
  string          registrationNumber = 2;
  optional string phone              = 3;
  optional string address            = 4;
  int32           stateId            = 5;
  int32           districtId         = 6;
  string          pincode            = 7;
}

message UpdateHealthInstituteProfileRes {
  string healthInstituteId = 1;
}

message GetHealthInstituteDetailsReq {
  string healthInstituteId = 1;
}

message HealthInstituteProfileDetails {
  int32           id                  = 1;
  string          healthInstituteName = 2;
  int32           healthInstituteType = 3;
  optional string registrationNumber  = 4;
  string          email               = 5;
  optional string phone               = 6;
  optional string address             = 7;
  optional int32  stateId             = 8;
  optional string stateName           = 9;
  optional int32  districtId          = 10;
  optional string districtName        = 11;
  optional string pincode             = 12;
}

message GetHealthInstituteDetailsRes {
  string                        healthInstituteId = 1;
  HealthInstituteProfileDetails profileDetails    = 2;
}

message MasterDataItem {
  int32  id   = 1;
  string name = 2;
  string code = 3;
}

message GetStatesReq {}

message GetStatesRes{
  repeated MasterDataItem states = 1;
}

message GetDistrictsReq {
  int32 stateId = 1;
}

message GetDistrictsRes {
  repeated MasterDataItem districts = 1;
}

message GetRegistrationCouncilReq {}

message GetRegistrationCouncilRes {
  repeated MasterDataItem registrationCouncils = 1;
}

message GetAppointDoctorMasterDataReq {}

message GetAppointDoctorMasterDataRes {
  repeated MasterDataItem departments        = 1;
  repeated MasterDataItem designations       = 2;
  repeated MasterDataItem consultationScopes = 3;
}

message AppointDoctorReq {
  uint32          healthInstitutePrimaryKey = 1;
  string          healthInstituteId         = 2;
  uint32          doctorPrimaryKey          = 3;
  string          doctorId                  = 4;
  string          departmentId              = 5;
  uint32          designation               = 6;
  string          joiningDate               = 7;
  uint32          consultationScope         = 8;
  optional string affiliationNotes          = 9;
}

message AppointDoctorRes {
  uint32 mappingId = 1;
}