apiVersion: v1
kind: Service
metadata:
  name: patient-service
  namespace: arogyalink
spec:
  selector:
    app: patient
  ports:
    - name: access-port
      protocol: TCP
      port: 8084
      targetPort: 8084
    - name: grpc-port
      protocol: TCP
      port: 50053
      targetPort: 50053
